var lasVegan =
[
 ["Lassie","Aziatische roerbakschotel met paprika",
  "https://lassie.nl/recepten/basmatirijst-extra/aziatische-roerbakschotel-puntpaprika-cashewnoten",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst Extra Vezels </a></li><li>4 eetlepels olie</li><li>1 zak gesneden prei (300 g) </li><li>200 g bloemkoolroosjes</li><li>3 puntpaprika’s, in ringen </li><li>250 g taugé </li><li>4 eetlepels teriyakisaus </li><li>125 g ongezouten cashewnoten, grof gehakt </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/475-Basmatirijst-Aziatische-roerbakschotel-met-puntpaprika-en-cashewnoten-kp.jpg",
  "4"],
 ["Lassie","Bloemkoolcurry met abrikozen en amandelen",
  "https://lassie.nl/recepten/half-volkoren-toverrijst/bloemkoolcurry-met-abrikozen-en-amandelen",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/half-volkoren-toverrijst'>Lassie Half volkoren Toverrijst</a> </li><li>1 bloemkool</li><li>2 kleine (rode) uien</li><li>8 gedroogde abrikozen</li><li>150 g bruine amandelen</li><li>3 eetlepels olie</li><li>1½ eetlepel kerriepoeder</li><li>200 ml groentebouillon</li><li>200 ml kokosmelk</li><li>2 - 3 eetlepels verse peterselie, grof gehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/433-Halfvolkoren-Toverrijst-Bloemkoolcurry-met-abrikozen-en-amandelen-kp.jpg",
  "4"],
 ["Lassie","Bulgursalade met komkommer &amp; paprika",
  "https://lassie.nl/recepten/bulgur/bulgursalade-met-komkommer-en-paprika",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/bulgur'>Lassie Bulgur</a></li><li> 2 eetlepels olijfolie</li><li> 1 zoete ui, gesnipperd</li><li> 1 eetlepel shoarmakruiden</li><li> ½ citroen, uitgeperst</li><li> 3 eetlepels verse peterselie, fijngehakt</li><li> 2 bosuitjes, in ringetjes</li><li> 1 komkommer, in blokjes</li><li>1 rode paprika, in blokjes<br /></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Bulgur-Bulgursalade-Met-Komkommer-En-Paprika.jpg",
  "4"],
 ["Lassie","Couscous met kruidige kikkererwtensaus",
  "https://lassie.nl/recepten/couscous-maroc/couscous-met-kruidige-kikkererwtensaus",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/couscous-maroc'>Lassie Couscous Maroc</a></li><li> 3 eetlepels olijfolie</li><li> 2 uien, gesnipperd</li><li> 2 theelepels gemalen komijn</li><li> 1 blikje tomatenpuree (70 g)</li><li> 1 blik kikkererwten (400 g), uitgelekt</li><li> 150 g knoflookolijven zonder pit</li><li> 3 eetlepels verse munt, fijngesneden</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Maroc-Couscous-Met-Kruidige-Kikkererwtensaus.jpg",
  "3"],
 ["Lassie","Gebakken bloemkool met kikkererwten",
  "https://lassie.nl/recepten/voorgestoomde-bulgur/gebakken-bloemkool-met-kikkererwten",
  "<ul><li>3 eetlepels olie</li><li>400 g bloemkoolroosjes (zak)</li><li>300 g kerstomaatjes, de grotere gehalveerd</li><li>1 potje kikkererwten (350 g), afgespoeld</li><li>50 g ontpitte kalamata-olijven </li><li>¼ theelepel gemalen kaneel </li><li>1 zak <a target='_blank' href='https://lassie.nl/producten/voorgestoomde-bulgur'>Lassie voorgestoomde bulgur (250 g)</a> </li><li>Extra nodig: bakplaat bekleed met bakpapier </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/540-Voorgestoomde-Bulgur-Gebakken-bloemkool-kikkererwten-tomaat-olijven.jpg",
  "2"],
 ["Lassie","Gestoofde Marokkaanse groenten",
  "https://lassie.nl/recepten/builtjes-parelcouscous/gestoofde-marokkaanse-groenten-olijven",
  "<ul><li>4 builtjes <a target='_blank' href='https://lassie.nl/producten/builtjes-parelcouscous'>Lassie Parelcouscous</a></li><li>3 eetlepels olie </li><li>2 uien, gesnipperd</li><li>1 eetlepel ras el hanout </li><li>4 pomodori tomaten, in stukjes</li><li>4 eetlepels zwarte olijven </li><li>1 klein blikje kikkererwten (150 g)</li><li>500 g regenboogwortels, geschild </li><li>1 courgette</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Parel-couscous-Gestoofde-Marokkaanse-groenten-olijven.jpg",
  "4"],
 ["Lassie","Groentecurry met quinoamix",
  "https://lassie.nl/recepten/zilvervliesrijst-quinoa-én-granen/groentecurry-met-quinoamix",
  "<ul><li> 1 pak<a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-quinoa-%C3%A9n-granen'> Lassie Zilvervliesrijst + Quinoa en Granen </a>(275 g)</li><li> 4 eetlepels rijstolie</li><li> 2 tenen knoflook, fijngehakt</li><li> 3 cm verse gember, geschild en geraspt</li><li> 1 eetlepel Madras kerriepoeder</li><li> 2 eetlepels geraspte kokos</li><li> 250 g rode linzen </li><li> 200 g wortel, in plakken</li><li> 1 courgette, in plakken</li><li> 300 g broccoliroosjes</li><li> 250 g cherrytomaatjes</li><li> 2 eetlepels verse koriander</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervlies-Quinoa-Granen-Groentecurry-Met-Quinoamix.jpg",
  "4"],
 ["Lassie","Groentepaella met gebakken tomaten",
  "https://lassie.nl/recepten/paella-rijst/groentepaella-met-gebakken-tomaten",
  "<ul><li>1 grote ui</li><li>1 grote teen knoflook</li><li>1 rode paprika</li><li>2 stengels bleekselderij</li><li>1 dunne wortel</li><li>1 courgette</li><li>1 envelopje met saffraan</li><li>5 eetlepels olijfolie</li><li>1 theelepel pikante paprikapoeder</li><li>225 g <a target='_blank' href='https://lassie.nl/producten/paella-rijst'>Lassie Paellarijst</a> </li><li>1 eetlepel tomatenpuree</li><li>6 tomaten</li><li>1 blik kikkererwten of rode kidneybonen, uitgelekt</li><li>2 eetlepels verse peterselie, fijngehakt</li><li>1 eetlepel verse oregano, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Paella-Rijst-Groente-Paella-Met-Gebakken-Tomaat.jpg",
  "4"],
 ["Lassie","Groentestoof met zilvervliesspeltmix",
  "https://lassie.nl/recepten/zilvervliesrijst-spelt-én-quinoa/groentestoof-met-zilvervliesspeltmix",
  "<ul><li>2 rode uien</li><li>2 tenen knoflook</li><li>400 g pompoen</li><li>1 pak<a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-spelt-%C3%A9n-quinoa'> Lassie Zilvervliesrijst + spelt en quinoa</a> (275 g)</li><li>3 eetlepels olijfolie</li><li>1 theelepel kurkuma</li><li>1½ theelepel gemalen komijn</li><li>400 g rode en gele cherrytomaatjes</li><li>sap en rasp van ½ biologische citroen</li><li>300 g panklare verse spinazie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Spelt-Quinoa-Groentestoof-Met-Zilvervliesspeltmix.jpg",
  "4"],
 ["Lassie","Groentestoof van zoete aardappel en champignons",
  "https://lassie.nl/recepten/zilvervliesrijst-spelt-én-quinoa/groentestoof-van-zoete-aardappel-en-champignons",
  "<ul><li> 300 ml (versgeperst) sinaasappelsap</li><li> 100 ml rode wijn</li><li> 3 volle eetlepels bruine suiker</li><li> 500 g zoete aardappelen, schoongeboend</li><li> 6 tenen knoflook</li><li> 1 rode paprika, in brede repen</li><li> 250 g kastanjechampignons</li><li> 1 rode peper, zonder zaadjes, in reepjes</li><li> 6 - 8 takjes tijm</li><li> 1 pak <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-spelt-%C3%A9n-quinoa'>Lassie Zilvervliesrijst + spelt en quinoa</a> (275 g)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Spelt-Quinoa-Groentestoof-Van-Zoete-Aardappel-En-Champignons.jpg",
  "4"],
 ["Lassie","Groentetajine met couscous",
  "https://lassie.nl/recepten/couscous-maroc/groentetajine-met-couscous",
  "<ul><li>4 eetlepels olijfolie</li><li>1 ui, in partjes</li><li>2 tenen knoflook, in plakjes</li><li>2 theelepels gemalen komijn</li><li>1 theelepel gemalen koriander </li><li>250 g wortel, in plakjes</li><li>1 rode paprika, in grove stukken</li><li>250 g sperziebonen, gehalveerd</li><li>75-100 g gemengde olijven</li><li>1 eetlepel verse tijmblaadjes</li><li>sap en rasp van 1 biologische citroen</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/couscous-maroc'>Lassie Gekruide Couscous Maroc </a>(250 g)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Maroc-Groentetaijnie-Met-Couscous.jpg",
  "2-3"],
 ["Lassie","Groentetajine met reuzenbonen en couscous",
  "https://lassie.nl/recepten/couscous/groentetajine-reuzenbonen",
  "<ul><li>3 eetlepels olie</li><li>1 ui, in dunne partjes</li><li>2 tenen knoflook, in plakjes</li><li>1 eetlepel ras el hanout</li><li>1 rode puntpaprika, in lange repen</li><li>1 courgette, in plakken</li><li>400 g pompoen, in stukjes</li><li>200 ml tomatensap</li><li>1 blik reuzenbonen (255 g)</li><li>275 g <a target='_blank' href='https://lassie.nl/producten/couscous'>Lassie Couscous</a> </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Groentetajine-En-Reuzenbonen.jpg",
  "4"],
 ["Lassie","Indiase linzensoep met aubergine",
  "https://lassie.nl/recepten/kortkokende-linzen-voor-soep/indiase-linzensoep-met-aubergine",
  "<ul><li>1 grote aubergine</li><li>3 eetlepels olie</li><li>1 grote ui, fijngesnipperd</li><li>2 tenen knoflook, fijngehakt</li><li>2 eetlepels Madras kerriepoeder</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/kortkokende-linzen-voor-soep'>Lassie Kortkokende linzen voor soep</a></li><li>250 g tomaten, in stukjes</li><li>400 ml kokosmelk </li><li>1 liter groentebouillon</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Linzen-Voor-Soep-Indiase-Linzensoep-Met-Aubergine.jpg",
  "4"],
 ["Lassie","Kikkererwtencurry met basmatirijst",
  "https://lassie.nl/recepten/basmatirijst-voordeelverpakking/kikkererwtencurry",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-voordeelverpakking'>Lassie Basmatirijst</a></li><li>3 eetlepels rijstolie</li><li>1 ui, gesnipperd</li><li>2 tenen knoflook, fijngehakt</li><li>1 eetlepel verse gember, geraspt</li><li>1 rode peper zonder zaadjes, fijngehakt</li><li>2 eetlepels Madras kerriepoeder</li><li>300 - 400 gram kikkererwten (uit blik of pot)</li><li>3 wortelen, in dunne plakjes</li><li>450 g panklare spinazie</li><li>100 ml kokosmelk</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/376-Basmatirijst-Kikkererwtencurry-kp.jpg",
  "4"],
 ["Lassie","Kleurige paprikasalsa met rijst en linzen",
  "https://lassie.nl/recepten/toverrijst/kleurige-paprikasalsa-met-rijst-en-linzen",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst</a></li><li>200 ml kokosmelk</li><li>4 eetlepels olijfolie</li><li>1 grote ui, gesnipperd</li><li>2 tenen knoflook, fijngehakt</li><li>300 – 400 g linzen (uitgelekt, uit pot of blik)</li><li>2 eetlepels sojasaus</li><li>3 kleine puntpaprika’s (rood, geel en oranje), in blokjes</li><li>sap van 1 sinaasappel</li><li>2 eetlepels verse koriander</li><li>1 theelepel sesamzaad</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-Kleurige-Paprikasalsa-Met-Rijst-En-Linzen.jpg",
  "4"],
 ["Lassie","Krokante tandoori tofublokjes",
  "https://lassie.nl/recepten/toverrijst/krokante-tandoori-tofu-blokjes-geroosterde-groente",
  "<ul><li>450 g tofu</li><li>2 gele paprika’s, in brede repen </li><li>1 bos groene asperges, 3 cm van de onderkant afgesneden</li><li>4 eetlepels olie</li><li>75 g tandoori specerijenpasta </li><li>10 g maïzena </li><li>300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst</a></li><li>100 g wortel julienne </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-kokant-gebakken-tofu-blokjes-met-geroosterde-gele-paprika.jpg",
  "4"],
 ["Lassie","Kruidige chopped salad en basilicum",
  "https://lassie.nl/recepten/builtjes-parelcouscous/kruidige-chopped-salad-basilicum",
  "<ul><li>4 builtjes <a target='_blank' href='https://lassie.nl/producten/builtjes-parelcouscous'>Lassie Parelcouscous </a></li><li>1 sjalot, fijngesnipperd </li><li>2 eetlepels witte wijnazijn</li><li>6 eetlepels extra vierge olijfolie</li><li>¼ (paarse) spitskool, in dunne reepjes </li><li>1 kleine komkommer, in blokjes van 1 bij 1 cm</li><li>250 g cocktailtomaten, in partjes </li><li>2 bospenen, in dunne plakjes </li><li>10 takjes basilicum, blaadjes grof gesneden</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Parel-couscous-Kruidige-chopped-salad-basilicum.jpg",
  "4"],
 ["Lassie","Kruidige rijst met paprikasaus &amp; cashewnoten",
  "https://lassie.nl/recepten/basmatirijst-voordeelverpakking/kruidige-rijst-paprikasaus-en-cashewnoten",
  "<ul><li> 3 eetlepels olijfolie</li><li> 1 grote ui, gesnipperd</li><li> 2 tenen knoflook, fijngehakt</li><li> 3 rode puntpaprika’s, in stukjes</li><li> 1 eetlepel milde paprikapoeder</li><li> 1 theelepel gemalen komijn</li><li> 1 theelepel kaneel</li><li> sap en rasp van 1 biologische sinaasappel</li><li> 200 ml tomatensap</li><li> 300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-voordeelverpakking'>Lassie Basmatirijst</a></li><li> 150 g ongezouten cashewnoten</li><li> 3 - 4 eetlepels sojasaus</li><li> 3 - 4 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirjist-Kruidige-Rijst-Met-Paprikasaus-En-Cashewnoten.jpg",
  "4"],
 ["Lassie","Libanese linzensoep met spinazie",
  "https://lassie.nl/recepten/kortkokende-linzen-voor-soep/libanese-linzensoep-met-spinazie",
  "<ul><li>3 eetlepels olijfolie</li><li>3 tenen knoflook, fijngehakt</li><li>1 theelepel grof zeezout</li><li>2 theelepes gemalen koriander</li><li>1 ui, gesnipperd</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/kortkokende-linzen-voor-soep'>Lassie kortkokende linzen voor soep</a></li><li>1½ liter groentebouillon</li><li>50 g pijnboompitten</li><li>300 g panklare spinazie</li><li>15 g verse koriander, fijngehakt</li><li>sap van 1 citroen</li><li>staafmixer</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Linzen-Voor-Soep-Libanese-Linzensoep-Met-Spinazie.jpg",
  "4"],
 ["Lassie","Linzencurry met groenten",
  "https://lassie.nl/recepten/basmatirijst-extra/linzencurry-met-groenten",
  "<ul><li>3 eetlepels rijstolie</li><li>1 grote ui, in dunne partjes</li><li>300 - 400 g linzen (uit pot of blik)</li><li>1 courgette, in blokjes </li><li>1 aubergine, in blokjes </li><li>400 g rijpe tomaten, in blokjes</li><li>200 ml kokosmelk</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst met extra vezels</a></li><li>1 eetlepel garam masala</li><li>2 eetlepels geraspte kokos</li><li>2 eetlepels verse koriander</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Linzencurry-Groenten-Basmatirijst-Extra-Vezels.jpg",
  "4"],
 ["Lassie","Madras curry met champignons",
  "https://lassie.nl/recepten/basmati-kokos-citroen/madras-curry-met-champignons-en-sojabonen",
  "<ul><li>3 eetlepels olie</li><li>1 bos bosuien, in stukken van 3 cm gesneden</li><li>350 g (mini)champignons </li><li>1 eetlepel currypoeder madras</li><li>225 ml tomato frito of tomatenblokjes</li><li>175 ml kokosmelk</li><li>200 g sojaboontjes (koeling)</li><li>1 stazak <a target='_blank' href='https://lassie.nl/producten/basmati-kokos-citroen'>Lassie Basmatirijst Kokos-Citroen</a> (200 g) </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Stazak-Basmati-Kokos-Citroengras-Madras-Curry-Metchampignons-En-Sojaboontjes.jpg",
  "2"],
 ["Lassie","Marokkaanse couscous met courgette",
  "https://lassie.nl/recepten/couscous-maroc/marokkaanse-couscous-met-courgette-en-sinaasappel",
  "<ul><li> 2 biologische sinaasappels</li><li> 275 g <a target='_blank' href='https://lassie.nl/producten/couscous-maroc'>Lassie Couscous Maroc</a></li><li> 1 courgette</li><li> 4 eetlepel geschaafde amandelen</li><li> 1 ui, grof gesnipperd</li><li> 2 eetlepels olijfolie</li><li> 1 theelepel gemalen komijn</li><li> 1 teen knoflook, geperst</li><li> 1 bosje verse basilicum</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Maroc-Marrokaanse-Couscous-Met-Courgette-En-Sinaasappel.jpg",
  "4"],
 ["Lassie","Mexicaanse burritobowl",
  "https://lassie.nl/recepten/toverrijst/mexicaanse-burritobowl-toverrijst",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst</a> </li><li>4 eetlepels olie</li><li>1 bakje uien gesneden (à 250 g) </li><li>2 puntpaprika’s, in stukken gesneden </li><li>2 blikjes bonenmix: crispy mais, rode kidney, lima &amp; black eyed bonen (à 160 g)</li><li>2 eetlepels burrito kruidenmix (zakje à 28 g) </li><li>200 g ijsbergsla met tuinkruiden (1 zak)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/512-Toverrijst-Mexicaanse-burritobowl-kp.jpg",
  "4"],
 ["Lassie","Oosterse rijstsalade met asperges &amp; taugé",
  "https://lassie.nl/recepten/basmatirijst-extra/oosterse-rijstsalade-met-asperges-en-tauge",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst Extra Vezels</a></li><li> 150 g peultjes</li><li> 250 g groene asperges</li><li> 2 eetlepels Oosterse wokolie</li><li> ½ komkommer, in reepjes</li><li> 3 bosuitjes, in schuine ringen</li><li> 100 g taugé</li><li> 50 ml woksaus ketjap-sesam</li><li> sap van 1 limoen</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Oosterse-Rijstsalade-Met-Asperges-En-Taugé.jpg",
  "4"],
 ["Lassie","Paprikabonensalsa met zilvervliesrijst",
  "https://lassie.nl/recepten/minuutje-zilvervliesrijst-quinoa-én-4-granen/paprikabonensalsa-met-zilvervliesrijst-quinoa-en-granen",
  "<ul><li> 1 eetlepel olijfolie</li><li> 2 bosuitjes, in grove stukken </li><li> 1 kleine rode puntpaprika, in reepjes</li><li> 1 kleine oranje puntpaprika, in reepjes</li><li> 1 kleine gele puntpaprika, in reepjes </li><li> 2 theelepels paprikapoeder</li><li> ½ theelepel gemalen komijn</li><li> 1 eetlepel verse oregano, grof gehakt</li><li> 160 g rode kidneybonen </li><li> 100 ml tomatensap</li><li> 1 bakje <a target='_blank' href='https://lassie.nl/producten/minuutje-zilvervliesrijst-quinoa-%C3%A9n-4-granen'>Lassie Minuutje Zilvervliesrijst + Quinoa én granen</a></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Minuutje-Zilvervliesrijst-Paprikabonensalsa-Met-Zilvervliesrijst-Quinoa-En-Granen.jpg",
  "1"],
 ["Lassie","Perzische rijst met linzen &amp; granaatappel",
  "https://lassie.nl/recepten/basmati-naturel/perzische-rijst-met-linzen-granaatappel-en-amandelen",
  "<ul><li>3 eetlepels olie</li><li>4 uien, in ringen </li><li>150 g wortel julienne </li><li>1 stazak <a target='_blank' href='https://lassie.nl/producten/basmati-naturel'>Lassie Basmatirijst naturel </a>(200 g) </li><li>1 blikje linzen (160 g), uitgelekt</li><li>1 theelepel gemalen kurkuma</li><li>½ eetlepel gemalen komijn</li><li>¼ theelepel gemalen kaneel</li><li>50 g amandelen, grof gehakt </li><li>50 g granaatappelpitjes </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Stazak-Basmati-Naturel-Perzische-Linzen-Rijst-Met-Wortel.jpg",
  "2"],
 ["Lassie","Pittige linzencurry met basmatirijst",
  "https://lassie.nl/recepten/basmatirijst-voordeelverpakking/pittige-linzencurry",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-voordeelverpakking'>Lassie Basmatirijst</a></li><li>3 eetlepels rijstolie</li><li>1 grote ui, gesnipperd</li><li>2 tenen knoflook, fijngehakt</li><li>1 eetlepel verse gember, geraspt</li><li>½ rode peper, zonder zaadjes, fijngehakt</li><li>1½ eetlepel Madras kerriepoeder </li><li>5 tomaten, in blokjes </li><li>200 ml kokosmelk</li><li>400 g linzen (pot of blik) </li><li>1 verse serehstengel, geplet (of 1 eetlepel citroensap)</li><li>2 eetlepels verse koriander, grof gehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Pittige-Linzencurry.jpg",
  "4"],
 ["Lassie","Pittige Thaise rijstsalade met asperges",
  "https://lassie.nl/recepten/pandanrijst-extra/pittige-thaise-rijstsalade-met-groene-asperges",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst Extra Vezels</a></li><li> 200 g peultjes</li><li> 100 g groene aspergetips</li><li> 3 eetlepels gembersiroop</li><li> 2 eetlepels azijn</li><li> 1 teen knoflook, fijngesneden</li><li> ½ tl chilipoeder</li><li> 1 blik maïskolfjes, uitgelekt</li><li> 1 rode ui, gesnipperd</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Pittige-Thaise-Rijstsalade-Met-Groene-Asperges.jpg",
  "4"],
 ["Lassie","Poké bowl buffet met wortelrijst en groenten",
  "https://lassie.nl/recepten/builtjes-pandanrijst/poke-bowl-buffet-wortelrijst-kleurige-groenten",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/builtjes-pandanrijst'> Lassie Pandanrijst</a> </li><li>750 ml wortelsap (fles)</li><li>1 rijpe avocado</li><li>4 snack komkommers, in blokjes</li><li>2 puntpaprika’s, in dunne ringen </li><li>1 bos radijs, in vieren </li><li>125 g wakame zeewiersalade (bakje) </li><li>40 g gefruite uitjes </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Pokébowl-buffet-wortelrijst-knapperige-groente.jpg",
  "4"],
 ["Lassie","Pompoencurry met rijst-linzenmix",
  "https://lassie.nl/recepten/zilvervliesrijst/pompoencurry-met-rijst-linzenmix",
  "<ul><li> 500 g flespompoen</li><li> 3 eetlepels rijstolie of olijfolie</li><li> 1 grote ui, grof gesnipperd</li><li> 2 tenen knoflook, fijngehakt</li><li> 1½ eetlepel kerriepoeder</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>1 blikje linzen (160 g), uitgelekt </li><li> 4 tomaten, in stukjes, of 1 blik tomaatstukjes</li><li> 200 ml kokosmelk</li><li> 100 g cashewnoten</li><li> 2 eetlepels verse koriander of verse peterselie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Linzen-Pompoencurry-Met-Rijst-Linzenmix.jpg",
  "4"],
 ["Lassie","Portobello met tomaten-zilvervliesrijst",
  "https://lassie.nl/recepten/zilvervliesrijst/portobello-met-tomaten-zilvervliesrijst",
  "<ul><li>4 eetlepels olijfolie</li><li>1 ui, gesnipperd</li><li>1 grote teen knoflook, fijngehakt</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>400 g tomaten, in stukjes</li><li>2 eetlepels verse oregano, fijngehakt</li><li>4 portobello’s</li><li>2 eetlepels balsamico-azijn</li><li>2 eetlepels hazelnoten, grof gehakt</li><li>1 bosuitje, in ringetjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Portobello-Met-Tomaten-Zilvervliesrijst.jpg",
  "4"],
 ["Lassie","Rijstsalade met aubergine en pindadressing",
  "https://lassie.nl/recepten/zilvervliesrijst-sorghum-én-wilde-rijst/rijstsalade-met-aubergine-en-pindadressing",
  "<ul><li>250 ml versgeperst sinaasappelsap</li><li>275 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-sorghum-én-wilde-rijst'>Lassie Zilvervliesrijst + sorghum en wilde rijst</a></li><li>1 grote aubergine</li><li>1 rode puntpaprika</li><li>1 gele puntpaprika</li><li>1 oranje puntpaprika</li><li>6 eetlepels olijfolie</li><li>3 - 4 eetlepels verse peterselie, fijngehakt</li><li>3 eetlepels ongezouten pinda’s</li><li>1 theelepel gemalen komijn</li><li>1 - 2 theelepels harissa</li><li>2 kropjes little gem sla</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Met-Sorghum-En-Wilde-Rijst-Rijstsalade-Met-Aubergine-En-Pindadressing.jpg",
  "4"],
 ["Lassie","Saffraanrisotto met pompoen &amp; amandel",
  "https://lassie.nl/recepten/risottorijst/saffraanrisotto-met-pompoen-en-amandel",
  "<ul><li>1 envelopje saffraandraadjes</li><li>3 eetlepels olijfolie</li><li>1 grote ui, gesnipperd</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/risottorijst'>Lassie Risottorijst</a></li><li>150 ml droge witte wijn</li><li>400 g pompoen (met schil), in blokjes</li><li>1 eetlepel verse oregano, fijngehakt</li><li>100 g bruine amandelen</li><li>300 g gewassen bladspinazie</li><li>3 eetlepels verse basilicum</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Risottorijst-Saffraanrisotto-Met-Pompoen-En-Amandel.jpg",
  "4"],
 ["Lassie","Salade van biet, wortel &amp; zilvervliesspeltmix",
  "https://lassie.nl/recepten/zilvervliesrijst-spelt-én-quinoa/salade-van-biet-wortel-en-zilvervliesspeltmix",
  "<ul><li> 2 eetlepels witte wijnazijn</li><li> 1 theelepel mosterd</li><li> 6 eetlepels neutrale olie </li><li> 250 g knolselderij, geschild</li><li> 250 g grote wortel, geschild</li><li> 1 rauw bietje, geschild</li><li> 275 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-spelt-%C3%A9n-quinoa'>Lassie Zilvervliesrijst + spelt en quinoa</a> </li><li> 2 tenen knoflook, fijngehakt</li><li> 1 theelepel kurkuma</li><li> 1 theelepel gemalen komijn</li><li> 1 theelepel kaneel</li><li> 250 ml cranberrysap</li><li> 25 g gepelde pistachenootjes, grofgehakt</li><li> 40 g veldsla</li><li> 1 bosuitje, in flinterdunne ringetjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Spelt-Quinoa-Salade-Van-Biet-Wortel-En-Zilvervliesspeltmix.jpg",
  "4-6"],
 ["Lassie","Snelle groenteroerbak met zilvervliesrijst",
  "https://lassie.nl/recepten/minuutje-zilvervliesrijst/snelle-groenteroerbak-met-zilvervliesrijst",
  "<ul><li> 2 eetlepels olie</li><li> ½ theelepel gemalen komijn</li><li> ½ theelepel gemberpoeder</li><li> 2 wortelen, geschild en in schuine plakken</li><li> 1 bosuitje, in grove stukken</li><li> 100 g broccoliroosjes</li><li>2 eetlepels sojasaus</li><li> 1 bakje <a target='_blank' href='https://lassie.nl/producten/minuutje-zilvervliesrijst'>Minuutje Zilvervliesrijst</a> (125 g)</li><li> 25 g gezouten cashewnoten</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Minuutje-Zilvervliesrijst-Snelle-Groenteroerbak-Met-Zilvervliesrijst.jpg",
  "1"],
 ["Lassie","Thaise curry van pompoen, sperzieboontjes en taugé",
  "https://lassie.nl/recepten/pandanrijst-extra/thaise-curry-van-pompoen-sperzieboontjes-en-taugé",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst Extra Vezels</a></li><li> 1 blik kokosmelk (400 ml)</li><li> 2 eetlepels Thaise rode currypasta</li><li> 1 kleine pompoen, geschild en in stukjes</li><li> 250 g sperzieboontjes, gehalveerd</li><li> 1 theelepel suiker</li><li> ½ limoen, uitgeperst</li><li> 250 g taugé</li><li> 1 bosje verse koriander, grof gesneden</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Thaise-Curry-Van-Pompoen-Sperzieboontjes-En-Taugé.jpg",
  "4"],
 ["Lassie","Thaise groentecurry met pompoen en cashewnoten",
  "https://lassie.nl/recepten/basmati-limoen-koriander/thaise-groentecurry-met-pompoen-en-cashewnoten",
  "<ul><li>2 eetlepels olie</li><li>1 prei, grof gesneden </li><li>70 g boemboe voor Thaise groene curry </li><li>400 g voorgesneden pompoen </li><li>200 ml kokosmelk </li><li>4 trostomaten, in partjes </li><li>150 g sugarsnaps</li><li>200 g taugé </li><li>1 stazak <a target='_blank' href='https://lassie.nl/producten/basmati-limoen-koriander'>Lassie Basmatirijst Limoen-Koriander</a> (200 g) </li><li>50 g cashewnoten </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Stazak-Basmati-Lime-Koriander-Thaise-Groentecurry-Met-Pompoen.jpg",
  "2"],
 ["Lassie","Thaise pompoensoep met pandanrijst",
  "https://lassie.nl/recepten/pandanrijst-extra/thaise-pompoensoep-met-pandanrijst",
  "<ul><li>200 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst met extra vezels</a></li><li>2 eetlepels rijstolie</li><li>2 sjalotjes, in dunne partjes</li><li>3 theelepels Thaise rode kruiden </li><li>400 ml kokosmelk</li><li>2 cm verse gember, in dunne plakjes</li><li>1 verse serehstengel, geplet</li><li>½ rode peper zonder zaadjes, in dunne reepjes</li><li>400 g pompoen (met schil), in blokjes</li><li>3 bosuitjes, in schuine stukken van 2 cm</li><li>2-3 eetlepels vissaus of 1 eetlepel sojasaus  </li><li>4 eetlepels verse koriander, grof gehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Thaise-Pompoensoep-Met-Pandanrijst.jpg",
  "4"],
 ["Lassie","Tofu met Chinese kool &amp; peultjes",
  "https://lassie.nl/recepten/zilvervliesrijst/tofu-met-chinese-kool",
  "<ul><li> 3 builtjes <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li> 200 g peultjes</li><li> 4 eetlepels olie</li><li> 1 ui, in ringen</li><li> 300 g blokjes tofu of vegetarische wokblokjes</li><li> 1 rode paprika, in reepjes</li><li> 3 eetlepels ketjap manis</li><li> ½ Chinese kool, in repen<br /></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Buitljes-Tofu-Met-Chinese-Kool.jpg",
  "3"],
 ["Lassie","Vega nasi goreng met boontjes",
  "https://lassie.nl/recepten/nasi-goreng/vega-nasi-goreng-met-boontjes",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/nasi-goreng'>Lassie Nasi Goreng</a></li><li> 375 g tofu, in blokjes</li><li> 300 ml zonnebloemolie</li><li> 1 grote ui, in ringen</li><li> 100 g boemboe voor nasi goreng </li><li>300 g sperzieboontjes, in stukjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Nasi-Goreng-Vega-Nasi-Goreng-Met-Boontjes.jpg",
  "3"],
 ["Lassie","Vegareepjes met tomaat en spruitjes",
  "https://lassie.nl/recepten/zilvervliesrijst/vegareepjes-met-tomaat-en-spruitjes",
  "<ul><li> 300 g spruitjes, gehalveerd</li><li> 400 g cherrytomaatjes, gehalveerd</li><li> 1 ui, gesnipperd</li><li> 1 teen knoflook, geperst</li><li> 330 g vega gegrilde stukjes</li><li> 300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>2 eetlepels olijfolie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Vegareepjes-Met-Tomaat-En-Spruitjes.jpg",
  "4"],
 ["Lassie","Zilvervliesrijst met asperges &amp; tofu",
  "https://lassie.nl/recepten/minuutje-zilvervliesrijst/zilvervliesrijst-met-groene-asperges-en-tofu",
  "<ul><li> 250 g groene asperges</li><li> 100 g tofu</li><li> 1½ eetlepel sesamolie</li><li> 2 eetlepels sojasaus</li><li> 1 kleine rode ui, in partjes</li><li> 1 kleine teen knoflook, in dunne plakjes</li><li> sap van ½ limoen</li><li> 1 bakje <a target='_blank' href='https://lassie.nl/producten/minuutje-zilvervliesrijst'>Lassie Minuutje Zilvervliesrijst</a></li><li> ½ eetlepel zwart en/of wit sesamzaad</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Minuutje-Zilvervliesrijst-Zilvervliesrijst-Met-Groene-Asperges-En-Tofu.jpg",
  "1"],
 ["Lassie","Zilvervliesrijst met bonen en aubergine",
  "https://lassie.nl/recepten/bio-zilvervliesrijst/zwarte-bonen-aubergine",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/bio-zilvervliesrijst'>Lassie BIO Zilvervliesrijst</a></li><li>2 middelgrote aubergines, in grove stukken </li><li>sap van 1 citroen</li><li>2 tenen knoflook, geperst</li><li>1 theelepel gemalen komijn</li><li>1 theelepel gemalen koriander</li><li>4 eetlepels olie</li><li>1 blik zwarte bonen (400 g)</li><li>5 bosuitjes, in stukjes </li><li>3 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Zwarte-bonen-en-aubergine.jpg",
  "4"],
 ["Lassie","Zwartebonenstoof met quinoamix",
  "https://lassie.nl/recepten/quinoa-mix-3-kleuren-quinoa/zwartebonenstoof-met-quinoamix",
  "<ul><li> 3 eetlepels olijfolie</li><li> 1 grote ui, gesnipperd</li><li> 2 tenen knoflook, fijngehakt</li><li> 500 g tomaten, in stukjes</li><li> 2 theelepels gemalen komijn</li><li> ½ theelepel gedroogde chilivlokken</li><li> 1 volle eetlepel verse oregano, fijngehakt</li><li> sap en rasp van 1 biologische sinaasappel</li><li> 4 wortelen, geschild en in kleine stukken </li><li> 1 gele paprika, in repen</li><li> 1 pak <a target='_blank' href='https://lassie.nl/producten/quinoa-mix-3-kleuren-quinoa'>Lassie Quinoamix</a> </li><li> 2 bosuitjes, in grove stukken </li><li> 2 blikken zwarte bonen (à 400 g), uitgelekt en afgespoeld</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/3-Kleuren-Quinoa-Zwartebonenstoof-Met-Quinoamix.jpg",
  "4"],
]