var lasVega =
[
 ["Lassie","Aubergine gevuld met pilav",
  "https://lassie.nl/recepten/bulgur/aubergine-gevuld-met-pilav",
  "<ul><li> 2 aubergines</li><li> 5 eetlepels olijfolie</li><li> 3 tenen knoflook, fijngehakt</li><li> 2 theelepels gemalen komijn</li><li> 2 theelepels gemalen kaneel</li><li> 1 pak <a target='_blank' href='https://lassie.nl/producten/bulgur'>Lassie Biologische Wereldgranen Bulgur</a></li><li> 500 ml groentebouillon</li><li> 6 verse dadels</li><li> 75 g gezouten, gepelde pistachenootjes</li><li> 200 g feta</li><li> 3 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Bulgur-Aubergine-Gevuld-Met-Pilav.jpg",
  "4"],
 ["Lassie","Aubergine met hazelnootrijst en feta",
  "https://lassie.nl/recepten/meergranenrijst/aubergine-met-hazelnootrijst-en-feta",
  "<ul><li>2 grote aubergines</li><li>2 eetlepels olijfolie</li><li>1 ui, gesnipperd</li><li>1 grote teen knoflook, fijngehakt</li><li>1 eetlepel ras el hanout</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/meergranenrijst'>Lassie Meergranenrijst</a> (275 g)</li><li>500 ml groentebouillon</li><li>50 g hazelnoten</li><li>3 eetlepels verse peterselie, fijngehakt</li><li>200 g feta, verkruimeld</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Meergranenrijst-Aubergine-Met-Hazelnootrijst-En-Feta.jpg",
  "4"],
 ["Lassie","Boerenkool-linzenrisotto met gegrilde portobello",
  "https://lassie.nl/recepten/zilvervliesrijst/boerenkool-linzenrisotto-met-gegrilde-portobello",
  "<ul><li>4 eetlepels olijfolie</li><li>1 grote ui, gesnipperd</li><li>2 tenen knoflook, fijngehakt</li><li>300 g panklare boerenkool</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>450 ml groentebouillon (van een tablet)</li><li>4 portobello‘s</li><li>2 eetlepels balsamico-azijn</li><li>75 g Parmezaanse kaas (stukje)</li><li>25 g boter</li><li>1 blikje linzen (160 g), uitgelekt </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Linzen-Boerenkool-Linzenrisotto-Met-Gegrilde-Portobello.jpg",
  "4"],
 ["Lassie","Bulgurpilav met courgette en feta",
  "https://lassie.nl/recepten/bulgur/bulgurpilav-met-courgette-en-feta",
  "<ul><li> 275 g<a target='_blank' href='https://lassie.nl/producten/bulgur'> Lassie Bulgur</a></li><li> 1 eetlepel olijfolie</li><li> 1 grote ui, gesnipperd</li><li> 500 ml groentebouillon </li><li> 1 courgette, in blokjes</li><li>300 g feta blokjes, uitgelekt</li><li> 3 eetlepels verse peterselie, fijngehakt</li><li> 50 g geschaafde amandelen, geroosterd</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Bulgur-Bulgurpilav-Met-Courgette-En-Feta.jpg",
  "4"],
 ["Lassie","Californian sushirol metkomkommer en sesam ",
  "https://lassie.nl/recepten/gele-rijst/californian-sushirol-gele-rijst-komkommer-sesam",
  "<ul><li>250 g <a target='_blank' href='https://lassie.nl/producten/gele-rijst'>Lassie Gele rijst</a> </li><li>7 eetlepels rijstazijn</li><li>8 eetlepels mayonaise </li><li>½ komkommer, geschild </li><li>1 rijpe avocado </li><li>4 norivellen </li><li>3 eetlepels geroosterd sesamzaad</li><li>100 g worteljulienne (zakje à 150 g)</li><li>Extra nodig: sushirolmat + kwastje</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Gele-rijst-Californian-sushirol-gele-rijst-komkommer-kidsproef.jpg",
  "4"],
 ["Lassie","Coleslaw met gegrilde avocado en veggie nuggets",
  "https://lassie.nl/recepten/voorgestoomde-bulgur/coleslaw-gegrilde-avocado-veggie-nuggets",
  "<ul><li>200 g gesneden spitskool (zak)</li><li>150 g worteljulienne (zakje) </li><li>3 eetlepels (plantaardige) mayonaise </li><li>1 volle theelepel grove mosterd </li><li>2 eetlepels wittewijnazijn</li><li>2 eetlepels olie </li><li>160 g veggie nuggets (schaal) </li><li>1 zak <a target='_blank' href='https://lassie.nl/producten/voorgestoomde-bulgur'>Lassie voorgestoomde bulgur (250 g)</a> </li><li>1 avocado </li><li>3 eetlepels grof geknipte biesloo</li><li>Extra nodig: grillpan</li></ul><p>Optioneel</p><ul><li>1 limoen, schoongeboend </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/538-Voorgestoomde-Bulgur-Coleslaw-bulgur-veggie-nuggets.jpg",
  "4"],
 ["Lassie","Couscous met gestoofde zomergroenten &amp; labne",
  "https://lassie.nl/recepten/couscous-maroc/couscous-maroc-gestoofde-zomergroenten-labne",
  "<ul><li>150 g Turkse yoghurt </li><li>250 g <a target='_blank' href='https://lassie.nl/producten/couscous-maroc'>Lassie Couscous Maroc</a> </li><li>3 eetlepels olie</li><li>2 paprika’s</li><li>1 kleine groene courgette </li><li>3 trostomaten, gehalveerd </li><li>1 sinaasappel, schoongeboend</li><li>75 g zaden- en pittenmix, geroosterd</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/546-Couscous-Maroc-Couscous-met-gestoofde-zomergroente-en-labne.jpg",
  "4"],
 ["Lassie","Couscoussalade met haloumi",
  "https://lassie.nl/recepten/couscous/couscoussalade-met-haloumi",
  "<ul><li> 6 tomaten</li><li> 6 verse dadels</li><li> 1 pak <a target='_blank' href='https://lassie.nl/producten/couscous'>Lassie Couscous </a></li><li> 1 eetlepel ras el hanout</li><li> 3 eetlepels verse peterselie, fijngehakt</li><li> sap en rasp van 1 biologische sinaasappel</li><li> 50 g gepelde pistachenootjes of bruine amandelen</li><li> 1 pakje haloumi</li><li> 2 eetlepels olijfolie</li><li> 75 g veldsla</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Couscoussalade-Met-Halloumi.jpg",
  "4"],
 ["Lassie","Couscoussalade met noten &amp; geitenkaas",
  "https://lassie.nl/recepten/couscous-maroc/couscoussalade-met-noten-en-geitenkaas",
  "<ul><li>1 pak <a target='_blank' href='https://lassie.nl/producten/couscous-maroc'>Lassie Gekruide Couscous Maroc</a> (250 g)</li><li>sap en rasp van 1 biologische sinaasappel</li><li>6 eetlepels olijfolie</li><li>4 tomaten</li><li>50 g gepelde hazelnoten of walnoten</li><li>2 eetlepels pompoenpitten</li><li>2 bosuitjes, in dunne ringetjes</li><li>2-3 eetlepels verse peterselie, fijngehakt</li><li>1 krop sla, bladeren gewassen</li><li>150 g zachte geitenkaas, verkruimeld</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Maroc-Couscoussalade-Met-Noten-En-Geitenkaas.jpg",
  "2-3"],
 ["Lassie","Curry van broccoli, bloemkool en couscous",
  "https://lassie.nl/recepten/couscous/curry-van-broccoli-bloemkool-en-couscous",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/couscous'>Lassie Couscous</a></li><li> 600 g bloemkool- en broccoliroosjes</li><li> 3 eetlepels olie</li><li> 1 zoete ui, in partjes</li><li> 2 eetlepels kerriepoeder</li><li> 50 g geschaafde amandelen</li><li> 250 g feta, in blokjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Curry-Van-Broccoli-Bloemkool-En-Couscous.jpg",
  "4"],
 ["Lassie","Eieren in Mediterrane groentesaus",
  "https://lassie.nl/recepten/zilvervliesrijst-quinoa-én-granen/eieren-in-mediterrance-groentesaus",
  "<ul><li> 6 grote eieren</li><li> 1 grote venkel</li><li> 1 envelopje saffraandraadjes</li><li> 1 pak <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-quinoa-%C3%A9n-granen'>Lassie Zilvervliesrijst + Quinoa en Granen</a> (275 g)</li><li> 4 eetlepels olijfolie</li><li> 3 grote tenen knoflook, fijngehakt</li><li> 1 rode paprika, in repen</li><li> 1 courgette, in blokjes</li><li> 500 g tomaten, in stukjes</li><li> 2 eetlepels verse oregano</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Quinoa-Granen-Eieren-In-Mediterrane-Groentesaus.jpg",
  "4"],
 ["Lassie","Falafel met komkommeryoghurt &amp; tomaat",
  "https://lassie.nl/recepten/toverrijst-extra/falafel-met-geroosterde-tomaat-en-komkommeryoghurt",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst-extra'>Lassie Toverrijst Extra vezels</a></li><li> ½ komkommer</li><li> 200 g Griekse yoghurt</li><li> 4 tomaten, gehalveerd</li><li> 1 eetlepel Provençaalse kruiden</li><li> 4 eetlepels olijfolie</li><li> 400 g falafel<br /></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-Extra-Falafel-Met-Geroosterde-Tomaat-En-Komkommeryoghurt.jpg",
  "4"],
 ["Lassie","Frisse limoenrijstbowl met falafel | met falafel",
  "https://lassie.nl/recepten/basmati-limoen-koriander/frisse-limoenrijstbowl-met-falafel",
  "<ul><li>3 eetlepels olie </li><li>1 schaal plantaardige falafelballetjes </li><li>1 stazak<a target='_blank' href='https://lassie.nl/producten/basmati-limoen-koriander'> Lassie Basmatirijst Limoen-Koriander </a>(200 g) </li><li>1 rijpe avocado</li><li>1 puntpaprika, in ringen</li><li>½ komkommer, in plakjes</li><li>1 rode ui, gesnipperd</li><li>6 takjes verse koriander</li><li>4 eetlepels Griekse yoghurt of (kokos)yoghurt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Stazak-Basmati-Lime-Koriander-Frisse-Limoenrijst-Bowlmet-Falafel.jpg",
  "2"],
 ["Lassie","Gado-gado met pandanrijst",
  "https://lassie.nl/recepten/pandanrijst-extra/gado-gado-met-pandanrijst",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst Extra Vezels</a></li><li> 200 ml kokosmelk</li><li> 50 ml gembersiroop</li><li> 200 g krieltjes in de schil, gehalveerd</li><li> 400 g mix van worteltjes en peultjes</li><li> 6 eieren</li><li> 1 komkommer</li><li> 200 g boemboe gado-gado</li><li> 1 zakje emping (soort kroepoek)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Gado-Gado-Met-Pandanrijst.jpg",
  "4"],
 ["Lassie","Gebakken schol met granaatappelsaus en couscous",
  "https://lassie.nl/recepten/couscous/gebakken-schol-met-granaatappelsaus-en-couscous",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/couscous'>Lassie Couscous </a></li><li> 4 scholfilets</li><li> sap van ½ citroen</li><li> 1 granaatappel</li><li> 5 eetlepels olijfolie</li><li> 1 rode ui, gesnipperd</li><li> 2 eetlepels sweet chilisauce</li><li> 3 eetlepels amandelschaafsel</li><li> 50 g havermout</li><li> 2 eetlepels verse oregano</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Couscous-Gebakken-Schol-Met-Granaatappelsaus-En-Couscous.jpg",
  "4"],
 ["Lassie","Gele rijst met Shanghai paksoi",
  "https://lassie.nl/recepten/gele-rijst/shanghai-paksoi-cashewnoten",
  "<ul><li>325 g Lassie <a target='_blank' href='https://lassie.nl/producten/gele-rijst'>Gele Rijst</a> </li><li> 2 struiken paksoi</li><li>3 eetlepels olie</li><li>2 tenen knoflook, in dunne plakken</li><li>1 grote (rode) ui, in dunne partjes</li><li>3 eetlepels Japanse sojasaus</li><li>1 eetlepel sesamolie</li><li>100 g ongezouten cashewnoten</li><li>3 - 4 eetlepels granaatappelpitjes</li><li>2 eetlepels verse koriander</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Gele-Rijst-Shanghai-Paksoi-En-Cashewnoten.jpg",
  "4"],
 ["Lassie","Geroosterde groenten met halloumi",
  "https://lassie.nl/recepten/zilvervliesrijst-sorghum-én-wilde-rijst/geroosterde-groenten-met-halloumi",
  "<ul><li>12 bospenen, geschild maar met een klein stukje groen eraan </li><li>400 g bloemkoolroosjes</li><li>200 g bimi (aspergebroccoli)</li><li>1 grote teen knoflook, geperst</li><li>2 theelepels (pikante) paprikapoeder</li><li>3 eetlepels verse oregano, grof gehakt</li><li>5 eetlepels olijfolie</li><li>275 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-sorghum-én-wilde-rijst'>Lassie Zilvervliesrijst + sorghum en wilde rijst</a> </li><li>225 g halloumi </li><li>2 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Met-Sorghum-En-Wilde-Rijst-Geroosterde-Groenten-Met-Halloumi.jpg",
  "4"],
 ["Lassie","Geroosterde pompoen met mozzarella",
  "https://lassie.nl/recepten/pandanrijst-extra/geroosterde-pompoen-mozzarella-tomaat-basilicumpesto",
  "<ul><li>1 zak pompoenblokjes (400 g) </li><li>1 zak paprikamix (3 stuks), in brede repen</li><li>3 eetlepels olie</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst Extra Vezels </a></li><li>2 tomaten, in stukjes</li><li>50 g verse groene pesto </li><li>2 zakjes minimozzarella, uitgelekt</li><li>50 g pijnboompitjes, geroosterd</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Vezels-Geroosterde-Pompoen-Mozzarella-En-Tomaat-Basilicumpesto.jpg",
  "4"],
 ["Lassie","Geroosterde venkel en radicchio met linzenmix",
  "https://lassie.nl/recepten/zilvervliesrijst/geroosterde-venkel-en-radicchio-met-linzenmix",
  "<ul><li> 2 middelgrote venkelknollen</li><li> 2 stevige kropjes radicchio</li><li> 4 tenen knoflook, gehalveerd</li><li> 1 eetlepel verse tijmblaadjes</li><li> 5 eetlepels olijfolie</li><li> 1 grote ui, gesnipperd</li><li> 4 theelepels ras el hanout</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>1 blikje linzen (160 g), uitgelekt </li><li> 4 eetlepels verse oregano en/of peterselie</li><li> 100 g gepelde walnoten</li><li> 1 eetlepel vloeibare honing</li><li> 4 eetlepels granaatappelpitjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Linzen-Geroosterde-Venkel-En-Radicchio-Met-Linzenmix.jpg",
  "4"],
 ["Lassie","Geroosterde wortels met linzenmix",
  "https://lassie.nl/recepten/zilvervliesrijst/geroosterde-wortels-met-linzenmix",
  "<ul><li> 200 g pastinaak</li><li> 400 g kleurige wortels (paars, geel en oranje)</li><li> 2 rode uien</li><li> 2 tenen knoflook</li><li> 1 eetlepel tijm</li><li> 2 theelepels grof zeezout</li><li> 3 eetlepels olijfolie</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Zilvervliesrijst </a></li><li> 250 g cherrytomaatjes</li><li> 50 g pompoenpitten</li><li> 100 g geraspte kaas</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Linzen-Geroosterde-Wortels-Met-Linzenmix.jpg",
  "4"],
 ["Lassie","Gevulde courgette met olijven &amp; feta",
  "https://lassie.nl/recepten/toverrijst/gevulde-courgette",
  "<ul><li>1 grote courgette</li> <li>3 eetlepels olijfolie</li> <li>1 ui, gesnipperd</li> <li>1 teen knoflook, fijngehakt</li> <li>200 g gekookte<a target='_blank' href='https://lassie.nl/producten/toverrijst'> Lassie Toverrijst</a> of<a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'> Zilvervliesrijst</a> (= 75 g ongekookte rijst)</li> <li>2 eetlepels verse peterselie, fijngehakt</li> <li>6 zwarte olijven zonder pit, in stukjes</li> <li>100 g feta, verkruimeld</li> <li>1 eetlepel tomatenpuree</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-Of-Zilvervliesrijst-Gevulde-Courgette.jpg",
  "2"],
 ["Lassie","Groene risotto met Gorgonzola",
  "https://lassie.nl/recepten/rapido-risotto/groene-risotto-met-gorgonzola",
  "<ul><li>350 gram <a target='_blank' href='https://lassie.nl/producten/rapido-risotto'>Rapido Risotto </a></li><li>1 klontje boter </li><li>1/2 rode ui, gesnipperd</li><li>60 g ontdooide spinazie </li><li>500 ml kippen-of groentenbouillon</li><li>100 gram gorgonzola, verkruimeld</li><li>60 gram geraspte Parmezaanse kaas</li><li>2 eetlepels pijnboompitjes, geroosterd</li><li>2 eetlepels gebakken uitjes </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rapido-Risotto-Groene-Risotto-Met-Gorgonzola.jpg",
  "4"],
 ["Lassie","Groentestoof met hazelnoten",
  "https://lassie.nl/recepten/zilvervliesrijst-spelt-én-quinoa/prei-bospeen-hazelnoten",
  "<ul><li>8 wortelen, geschild</li><li>275 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-spelt-én-quinoa'>Lassie Zilvervliesrijst + Spelt én Quinoa</a> </li><li>25 g boter </li><li>1 rode ui, in 8 partjes</li><li>2 - 3 dunne preien, gewassen en in stukken van 6 – 8 cm</li><li>200 g spruitjes</li><li>1 eetlepel verse tijm</li><li>1 - 2 eetlepel citroensap</li><li>150 g hazelnoten</li><li>1 - 1½ eetlepel vloeibare honing</li><li>1 theelepel kurkuma</li><li>100 g crème fraîche </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Spelt-Én-Quinoa-Prei-Bospeen-Hazelnoten.jpg",
  "4"],
 ["Lassie","Herfstschotel met pompoen &amp; kaas",
  "https://lassie.nl/recepten/zilvervliesrijst/herfstschotel-met-pompoen-en-blauwe-kaas",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li> 1 kleine flespompoen (ca. 1 kg), schoongeboend</li><li> 2 rode uien, in parten</li><li> 3 - 4 eetlepels olijfolie</li><li> 1 teen knoflook, geraspt</li><li> 2 theelepels tijm</li><li> 100 g walnoten</li><li> 200 g blauwe kaas<br /></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Hersftschotel-Met-Pompoen-En-Blauwe-Kaas.jpg",
  "4"],
 ["Lassie","Indiase notenpilav met basmatirijst",
  "https://lassie.nl/recepten/basmatirijst-voordeelverpakking/indiase-notenpilav",
  "<ul><li> 1 envelopje saffraandraadjes</li><li> 500 ml kippenbouillon</li><li> rasp van 1 biologische sinaasappel</li><li> 4 eetlepels neutrale olie</li><li> 250 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-voordeelverpakking'>Lassie Basmatirijst</a></li><li> 50 g rozijnen</li><li> 50 g gedroogde abrikozen, in stukjes</li><li> 2 eieren</li><li> 25 g geschaafde amandelen, grof gehakt</li><li> 25 g gepelde pistachenootjes, gehakt</li><li> 2 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Indiase-Notenpilav.jpg",
  "4"],
 ["Lassie","Indische groentestoof met kerrie-eieren",
  "https://lassie.nl/recepten/pandanrijst-extra/indische-groentestoof-met-kerrie-eieren",
  "<ul><li> 800 g Chinese groentemix</li><li> 6 eieren</li><li> 300 g<a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'> Lassie Pandanrijst</a></li><li> 1 bakje boemboe sajoer groenten</li><li> 200 ml kokosmelk</li><li>1 eetlepels bakolie </li><li> 1 eetlepel kerriepoeder</li><li> 1 - 2 eetlepels tarwebloem</li><li> 4 eetlepels seroendeng</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Indische-Groentestoof-Met-Kerrie-Eieren.jpg",
  "4"],
 ["Lassie","Italiaans groentepotje met mozzarella",
  "https://lassie.nl/recepten/gele-rijst/italiaans-groentepotje-met-mozzarella",
  "<ul><li> 325 g Lassie<a target='_blank' href='https://lassie.nl/producten/gele-rijst'> Gele Rijst</a></li><li> 1 struik bleekselderij, in stukken</li><li> 4 eetlepels olijfolie</li><li> 2 sjalotjes, in ringen</li><li> 1 aubergine, in blokjes</li><li> 6 tomaten, in parten</li><li> 2 eetlepels balsamico-azijn</li><li> 2 bollen mozzarella (à 125 g), in blokjes</li><li> 50 g Parmezaanse kaas, geraspt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Gele-Rijst-Italiaanse-Groenten-Met-Mozzarella.jpg",
  "4"],
 ["Lassie","Italiaanse auberginetournedos",
  "https://lassie.nl/recepten/builtjes-half-volkoren-toverrijst/aubergine-tournedos-tomatensaus-kappertjes",
  "<ul><li>5 eetlepels olie</li><li>1 teen knoflook, geperst</li><li>1 eetlepel verse rozemarijn, grof gehakt </li><li>1 blik tomatenblokjes (400 ml)</li><li>3 aubergines, in dikke plakken</li><li>4 <a target='_blank' href='https://lassie.nl/producten/builtjes-half-volkoren-toverrijst'>Builtjes Half volkoren Toverrijst</a><br /></li><li>2 eetlepels kappertjes </li><li>80 g amandelen, grof gehakt</li><li>50 g geschaafde Parmezaanse kaas </li><li>1 zakje rucola</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Half-Volkoren-Toverrijst-Italiaanse-Aubergine-Tournedos-Met-Tomatensaus-En-Kappertjes.jpg",
  "4"],
 ["Lassie","Italiaanse ovenschotel met tomaat &amp; kaas ",
  "https://lassie.nl/recepten/half-volkoren-toverrijst/italiaanse-ovenschotel-met-tomaat-kaas-en-oregano",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/half-volkoren-toverrijst'>Lassie halfvolkoren toverrijst</a> </li><li>4 eetlepels olie</li><li>2 rode uien, gesnipperd</li><li>2 tenen knoflook, fijngehakt </li><li>1 courgette, in plakken </li><li>500 g trostomaten, in partjes </li><li>1 eetlepel gedroogde Italiaanse kruiden </li><li>100 g belegen kaas, geraspt </li><li>2 bollen buffelmozzarella, in plakken</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/450-Halfvolkoren-Toverrijst-Italiaanse-ovenschotel-met-tomaat-kp.jpg",
  "4"],
 ["Lassie","Italiaanse rijst met paprika &amp; mozzarella",
  "https://lassie.nl/recepten/toverrijst/italiaanse-rijst-met-paprika-en-mozzarella",
  "<ul><li> 1 rode paprika, in reepjes </li><li> 1 gele paprika, in reepjes</li><li> 1 groene paprika, in reepjes </li><li> 2 uien, gesnipperd</li><li> 150 g mini-mozzarella, uitgelekt</li><li> 300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst</a></li><li> 250 ml Italiaanse tomatensaus</li><li> 1 eetlepel gedroogde Italiaanse kruiden</li><li>2 eetlepels olijfolie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-Italiaanse-Rijst-Met-Paprika-En-Mozzarella.jpg",
  "4"],
 ["Lassie","Japanse roerbak met tofu en shii-take",
  "https://lassie.nl/recepten/basmatirijst-extra/japanse-roerbak-met-tofu-en-shii-take",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst Extra Vezels</a></li><li> 1 eetlepels olie</li><li> 350 g tofu, in kleine blokjes</li><li> 150 g shii-take, in plakjes</li><li> 100 ml teriyaki (wok)saus of marinade</li><li> 1 grote wortel, in reepjes</li><li> 200 g peultjes, gehalveerd</li><li> 1 ei, losgeklopt</li><li> 2 bosuitjes, in smalle ringetjes</li><li> 4 eetlepels sesamzaad</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Extra-Japanse-Roerbak-Met-Tofu-En-Shii-Take.jpg",
  "4"],
 ["Lassie","Kerrierijst met boontjes &amp; cashewnoten",
  "https://lassie.nl/recepten/panklaar-toverrijst/kerrierijst-met-boontjes-en-cashewnoten",
  "<ul><li>2 eieren</li><li>½ rode peper</li><li>100 ml romige kokosmelk</li><li>1½ eetlepels neutrale olie</li><li>1 teen knoflook, fijngehakt</li><li>1 eetlepel kerriepoeder</li><li>1 ui, in dunne partjes</li><li>150 g sperziebonen, gehalveerd</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/panklaar-toverrijst'>Lassie Panklaar Toverrijst</a> </li><li>40 g gezouten cashewnoten</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rijke-Roerbakrijst-Wit-Kerrierijst-Met-Boontjes-En-Cashewnoten.jpg",
  "2"],
 ["Lassie","Kruidige linzensoep met feta &amp; hazelnoten",
  "https://lassie.nl/recepten/kortkokende-linzen-voor-soep/kruidige-linzensoep-met-feta-en-hazelnoten",
  "<ul><li>3 eetlepels olijfolie</li><li>1 grote ui, fijngesnipperd</li><li>2 grote tenen knoflook, fijngehakt</li><li>1 eetlepel jalapeño peper (uit pot), fijngehakt</li><li>300 g <a target='_blank' href='https://lassie.nl/producten/kortkokende-linzen-voor-soep'>Lassie Kortkokende linzen voor soep</a></li><li>500 g tomaten, in stukjes</li><li>1¼ - 1½ liter groentebouillon</li><li>100 g hazelnoten</li><li>4 eetlepels verse peterselie, fijngehakt</li><li>3 eetlepels verse oregano, fijngehakt</li><li>200 g feta, verkruimeld</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Kk-Linzen-Voor-Soep-Kruidige-Linzensoep-Met-Feta-En-Hazelnoten.jpg",
  "4"],
 ["Lassie","Massala eieren met bloemkool en rijst",
  "https://lassie.nl/recepten/toverrijst/massala-eieren-bloemkool-toverrijst",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst</a> </li><li>600 g bloemkoolroosjes </li><li>4 eieren </li><li>2 el (olijf)olie </li><li>1½ el massala </li><li>1 rode ui, in ringen </li><li>2 teentjes knoflook, geperst</li><li>4 el piccalilly</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/570-Toverrijst-Toverrijst-met-massala-eieren-en-bloemkool.jpg",
  "4"],
 ["Lassie","Mediterrane groenten met feta",
  "https://lassie.nl/recepten/minuutje-zilvervliesrijst/mediterrane-groenten",
  "<ul><li> 2 porties <a target='_blank' href='https://lassie.nl/producten/minuutje-zilvervliesrijst'>Lassie Minuutje Zilvervliesrijst</a></li><li> 2 eetlepels olijfolie</li><li> 1 rode ui, gesnipperd</li><li> 2 theelepels Italiaanse kruiden</li><li> 1 rode paprika, in stukjes</li><li> 1 courgette, in reepjes</li><li> 150 g feta, in blokjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Minuutje-Zilvervliesrijst-Mediterrane-Groenten-Met-Feta.jpg",
  "2"],
 ["Lassie","Mediterrane groenten met gele rijst",
  "https://lassie.nl/recepten/gele-rijst/mediterrane-groenten-met-gele-rijst",
  "<ul><li> 325 g <a target='_blank' href='https://lassie.nl/producten/gele-rijst'>Lassie Gele rijst</a></li><li> 4 eetlepels olijfolie</li><li> 2 rode uien, in plakjes</li><li> 1 gele paprika, in stukken</li><li> 2 tenen knoflook, fijngesneden</li><li> 2 theelepels Italiaanse kruiden</li><li> 1 blik tomatenblokjes (400 g)</li><li> 500 g broccoli, in roosjes</li><li> 100 g jonge kaas, geraspt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Gele-Rijst-Mediterrane-Groenten-Met-Gele-Rijst.jpg",
  "4"],
 ["Lassie","Mexicaanse rijstschotel met jonge kaas",
  "https://lassie.nl/recepten/minuutje-zilvervliesrijst/mexicaanse-rijstschotel",
  "<ul><li> 100 g Mexico melange (paprika, doperwt en maïs, diepvries)</li><li> 6 cherrytomaatjes, gehalveerd</li><li> 1/2 komkommer, in lange plakjes</li><li> 50 g jonge kaas, in dikke reepjes</li><li> 1 portie <a target='_blank' href='https://lassie.nl/producten/minuutje-zilvervliesrijst'>Lassie Zilvervliesrijst Minuutje</a></li><li>2 eetlepels tomatenketchup</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/147-MInuutje-Zilvervliesrijst-Mexicaanse-rijstschotel-nieuw.jpg",
  "1"],
 ["Lassie","Nasi goreng met pittige omelet &amp; broccoli",
  "https://lassie.nl/recepten/zilvervliesrijst/nasi-goreng-met-pittige-omelet-en-broccoli",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li> 5 eieren</li><li> 1 teen knoflook</li><li> 1 tl sambal badjak</li><li> 3 - 4 eetlepels verse koriander of peterselie, fijngehakt</li><li> 3 - 4 eetlepels (arachide, rijst of zonnebloem)olie</li><li> 450 g broccoli</li><li> 1 ui, in halve ringen</li><li> 100 g boemboe nasi goreng</li><li> 1 rode paprika, in blokjes</li><li> 100 g taugé</li><li> 50 g vliespinda’s</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/77-Nasi-Goreng-Nasi-goreng-met-pittige-omelet-en-broccoli-nieuw.jpg",
  "4"],
 ["Lassie","Notenpilav met aubergine",
  "https://lassie.nl/recepten/gele-rijst/notenpilav-met-aubergine",
  "<ul><li>2 grote aubergines </li><li>50 g rozijnen</li><li>50 g gedroogde abrikozen, in kleine stukjes</li><li>100 ml medium dry sherry</li><li>1 eetlepel paprikapoeder</li><li>1 theelepel gemberpoeder</li><li>1 theelepel gemalen komijn</li><li>4 eetlepels olijfolie</li><li>1 grote ui, gesnipperd</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/gele-rijst'>Lassie Gele rijst</a> (275 g)</li><li>50 g gepelde pistachenootjes, grofgehakt</li><li>4 eetlepels granaatappelpitjes</li><li>2 eetlepels verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Gele-Rijst-Notenpilav-Met-Aubergine.jpg",
  "4"],
 ["Lassie","Thaise curry met pastinaak en cashewnoten",
  "https://lassie.nl/recepten/notenrijst/notenrijst-pastinaak-curry-cashewnoten",
  "<ul><li>275 g <a target='_blank' href='https://lassie.nl/producten/notenrijst'> Lassie Notenrijst</a></li><li>3 eetlepels olie</li><li>2 uien, grof gesneden </li><li>4 pastinaken, geschild </li><li>70 g Thaise rode currykruidenpasta (pakje)</li><li>1 blik kokosmelk (400 ml) </li><li>1 blik tomatenblokjes met knoflook (400 ml) </li><li>6 eetlepels koriander, grof gesneden </li><li>100 g cashewnoten, licht geroosterd </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/528-Notenrijst-Rode-pastinaakcurry-cashewnoten-koriander-notenrijst.jpg",
  "4"],
 ["Lassie","Notenrijstsalade met paprika &amp; geitenkaas",
  "https://lassie.nl/recepten/notenrijst/notenrijstsalade-met-paprika-en-geitenkaas",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/notenrijst'>Lassie Notenrijst</a></li><li> 3 eetlepels olijfolie</li><li> 2 eetlepels witte wijnazijn</li><li> 1 eetlepel dijonmosterd</li><li> 1 sjalotje, gesnipperd</li><li> 1 komkommer, in halve plakjes</li><li> 1 rode paprika, in stukjes</li><li> 75 g rucola</li><li> 200 g geitenkaas<br /></li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Notenrijst-Notenrijstsalade-Met-Prprika-En-Geitenkaas.jpg",
  "4"],
 ["Lassie","Omelet met groenterijst",
  "https://lassie.nl/recepten/toverrijst/omelet-met-groenterijst",
  "<ul><li> 400 g groentemix met prei</li><li> 1 rode paprika, in blokjes</li><li> 6 eieren</li><li> 100 g geraspte kaas</li><li> 4 eetlepels melk</li><li> 300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst'>Lassie Toverrijst </a></li><li> olijfolie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rijke-Roerbakrijst-Wit-Omelet-Met-Groenterijst.jpg",
  "4"],
 ["Lassie","Oosterse Bentobox met rijst, ei en sojadip ",
  "https://lassie.nl/recepten/builtjes-basmatirijst/oosterse-bentobox-rijst-ei-sojadip",
  "<ul><li>175 g <a target='_blank' href='https://lassie.nl/producten/builtjes-basmatirijst'>Lassie Basmatirijst</a> </li><li>3 eetlepels mayonaise </li><li>4 hardgekookte eieren, gepeld</li><li>4 eetlepels sojasaus</li><li>2 eetlepels gembersiroop</li><li>12 sweetpeppers met verse kaas (bakje à 175 g)</li><li>80 g zeewier krokantjes, (à 125 g) </li><li>150 g wortel julienne (1 zakje)</li><li>Extra nodig: 4 bentoboxen of broodtrommels + 4 kleine afsluitbare kleine bakjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Oosterse-bentobox-rijst-ei-sojadipje.jpg",
  "4"],
 ["Lassie","Oosterse paksoi met sesam en een eitje",
  "https://lassie.nl/recepten/meergranenrijst/meergranenrijst-oosterse-paksoi-sesam",
  "<ul><li>275 g <a target='_blank' href='https://lassie.nl/producten/meergranenrijst'>Lassie Meergranenrijst</a></li><li>4 eetlepels (sesam)olie</li><li>2 stuks Shanghai paksoi (of 1 gewone paksoi), grof gesneden</li><li>250 g taugé</li><li>2 eetlepels (zwart) sesamzaad </li><li>2 eetlepels ketjap</li><li>1 eetlepel gehakte gember (potje 100 g)</li><li>4 eieren </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/526-Meergranenrijst-Oosterse-meergranenrijst-Shanghai-paksoi-sesam.jpg",
  "4"],
 ["Lassie","Oosterse rijst met shiitake en gember",
  "https://lassie.nl/recepten/panklaar-zilvervliesrijst/oosterse-rijst-met-shiitake-en-gember",
  "<ul><li>2 pakken <a target='_blank' href='https://lassie.nl/producten/panklaar-zilvervliesrijst'>Lassie Panklaar Zilvervliesrijst</a> </li><li>3 eetlepels olie</li><li>2 tenen knoflook, geperst</li><li>3 cm verse gember, geraspt</li><li>150 g wortel, in dunne reepjes </li><li>1 gele paprika, in stukjes</li><li>350 shiitake, in grove stukken </li><li>70 ml sojasaus</li><li>1-2 theelepels sambal manis</li><li>2 bosuitjes, in ringetjes </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rijke-Roerbakrijst-Wit-Oosterse-Rijst-Met-Shiitake-En-Gember.jpg",
  "4"],
 ["Lassie","Paddenstoelenrisotto met cherrytomaatjes",
  "https://lassie.nl/recepten/rapido-risotto/paddenstoelenrisotto-met-cherrytomaatjes",
  "<ul><li>1 portobello</li><li>2 eetlepels olijfolie</li><li>1 teen knoflook, in plakjes</li><li>½ eetlepel citroensap</li><li>1 kleine ui, gesnipperd</li><li>175 g <a target='_blank' href='https://lassie.nl/producten/rapido-risotto'>Rapido Risotto </a></li><li>1 eetlepel verse tijmblaadjes</li><li>250 g cherrytomaatjes, gehalveerd</li><li>4 eetlepels zure room</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rapido-Risotto-Paddenstoelenrisotto-Met-Cherrytomaatjes.jpg",
  "2"],
 ["Lassie","Paella van spinazie, rozijnen en kikkererwten",
  "https://lassie.nl/recepten/pronto-paella/spinazie-rozijnen-kikkererwten-paella",
  "<ul><li>3 eetlepels olijfolie</li><li>2 gele paprika’s, in blokjes</li><li>½ eetlepel ras el hanout</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/pronto-paella'>Lassie Pronto Paella</a> (300g)</li><li>1 blik kikkererwten (400 gram), uitgelekt</li><li>100 g rozijnen</li><li>400 g panklare spinazie</li><li>3 eetlepels geschaafde amandelen</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Spinazie-rozijnen-en-kikkererwten-Paella.jpg",
  "4"],
 ["Lassie","Pandanrijst met Aziatische omelet",
  "https://lassie.nl/recepten/pandanrijst-extra/aziatische-omelet-groente-vissaus",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/pandanrijst-extra'>Lassie Pandanrijst Extra Vezels </a></li><li>150 g wortel- en bietenjulienne</li><li>150 g taugé</li><li>1 kropje little gem, fijngesneden</li><li>3 eetlepels vissaus</li><li>4 eetlepels olie</li><li>2 bosuitjes, fijngesneden, wit en groen apart gehouden</li><li>6 eieren, losgeklopt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Extra-Vezels-Aziatische-Omelet-Gevuld-Met-Knapperige-Kleine-Gronete-Vissaus.jpg",
  "4"],
 ["Lassie","Paprika gevuld met noten-rozijnenrijst",
  "https://lassie.nl/recepten/notenrijst/paprika-gevuld-met-noten-rozijnenrijst",
  "<ul><li> 4 rode paprika’s</li><li> 1 ui, gesnipperd</li><li> 2 eetlepels olijfolie</li><li> 1 teen knoflook, geperst</li><li> 1 eetlepel shoarmakruiden</li><li> 1 blik kikkererwten, vocht opgevangen</li><li> 300 g feta, in kleine blokjes</li><li> eetlepels verse munt, fijngesneden</li><li> 275 g <a target='_blank' href='https://lassie.nl/producten/notenrijst'>Lassie Notenrijst</a></li><li> 75 g rozijnen</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Notenrijst-Paprika-Gevuld-Met-Noten-Rozijnenrijst.jpg",
  "4"],
 ["Lassie","Pittige Indiase rijst met yoghurt",
  "https://lassie.nl/recepten/basmatirijst-extra/pittige-indiase-rijst-met-yoghurt",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst</a></li><li>1 stukje verse gember</li><li> 1 verse groene of rode peper</li><li> 150 g Griekse yoghurt</li><li> 2 eetlepels rode linzen</li><li> 2 theelepels mosterdzaadjes</li><li> 2 theelepels komijnzaadjes</li><li> 1 theelepel chilipeper (uit een molentje)</li><li> 4 eetlepels rijstolie</li><li> 1 eetlepel verse koriander of peterselie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmatirijst-Pittige-Indiase-Rijst-Mer-Yoghurt.jpg",
  "4"],
 ["Lassie","Portobello met tomaat en feta",
  "https://lassie.nl/recepten/builtjes-zilvervliesrijst/portobello-tomaat-feta",
  "<ul><li>4 builtjes <a target='_blank' href='https://lassie.nl/producten/builtjes-zilvervliesrijst'>Lassie Zilvervliesrijst </a></li><li>1 (biologische) sinaasappel</li><li>3 eetlepels olie</li><li>2 uien, in dunne partjes</li><li>4 portobello’s, in dikke repen</li><li>2 eetlepels verse Italiaanse kruiden, fijngehakt</li><li>50 g hazelnoten, grof gehakt</li><li>6 cocktailtomaten, in vieren</li><li>100 g Griekse feta, verkruimeld</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Portobello-En-Tomaat.jpg",
  "4"],
 ["Lassie","Quinoa schotel van aardappel &amp; tomaat",
  "https://lassie.nl/recepten/quinoa/schotel-van-aardappel-quinoa-en-tomaat",
  "<ul><li> 140 g <a target='_blank' href='https://lassie.nl/producten/quinoa'>Lassie Quinoa</a></li><li> 3 eetlepels olie</li><li> 450 g Voorgekookte aardappelblokjes</li><li> 1 ui, gesnipperd</li><li> 350 g cherrytomaatjes, gehalveerd</li><li> 1 theelepel gedroogde oregano</li><li> 1 teen knoflook, fijngehakt</li><li> 6 eieren</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Quinoa-Schotel-Van-Aardappel-En-Quinoa-En-Tomaat.jpg",
  "4"],
 ["Lassie","Quinoasalade met asperges, paprika en feta",
  "https://lassie.nl/recepten/quinoa/quinoasalade-met-asperges-paprika-en-feta",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/quinoa'>Lassie Quinoa</a></li><li> 200 g groene asperges</li><li> 4 geroosterde paprika’s (uit pot)</li><li> 60 ml balsamico dressing</li><li> 3 bosuitjes, in smalle ringen</li><li> 75 - 100 g rucola, uitgezocht</li><li> 300 g feta, in blokjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Quinoa-Quinoasalade-Met-Asperges-Paprika-En-Feta.jpg",
  "4"],
 ["Lassie","Quinoa met geroosterde bietjes en geitenkaas ",
  "https://lassie.nl/recepten/builtjes-quinoa/geroosterde-bietjes-geitenkaas",
  "<ul><li>750 g rauwe rode en/of gele bieten, geschild en in 12 partjes</li><li>2 uien, in 8 partjes gesneden</li><li>3 eetlepels verse oregano, grof gehakt</li><li>2 - 3 eetlepels olie</li><li>2 - 3 eetlepels balsamico azijn</li><li>3 a 4 builtjes <a target='_blank' href='https://lassie.nl/producten/builtjes-quinoa'>Lassie Quinoa </a></li><li>200 g kleine ronde zachte geitenkaasplakken</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Quinoa-Geroosterde-Bietjes-En-Geitenkaas.jpg",
  "4"],
 ["Lassie","Quinoa met geroosterde groenten",
  "https://lassie.nl/recepten/quinoa-mix-3-kleuren-quinoa/quinoa-met-geroosterde-groenten",
  "<ul><li>1 courgette</li><li>1 aubergine</li><li>1 rode paprika</li><li>1 gele paprika</li><li>2 tenen knoflook, in plakjes</li><li>1 grote ui, grof gesnipperd</li><li>250 g cherrytomaatjes</li><li>1 eetlepel verse oregano, fijngehakt</li><li>1 eetlepel verse tijmblaadjes</li><li>2 eetlepels balsamico azijn</li><li>4 - 5 eetlepels olijfolie</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/quinoa-mix-3-kleuren-quinoa'>Lassie Quinoamix</a> </li><li>100 g gemengde olijven</li><li>200 g feta, in blokjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/217-3-kleuren-Quinoa-Quinoa-met-geroosterde-groenten.jpg",
  "4"],
 ["Lassie","Rijst-linzenmix met doperwtjes en groene asperges",
  "https://lassie.nl/recepten/zilvervliesrijst/rijst-linzenmix-met-doperwtjes-en-groene-asperges",
  "<ul><li> 275 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li>1 blikje linzen (160 g), uitgelekt </li><li> 500 g groene asperges</li><li> 3 eetlepels olijfolie</li><li> 1 grote ui, gesnipperd</li><li> 200 g doperwtjes (diepvries of vers)</li><li> 75 g Parmezaanse kaas (stukje)</li><li> 3 eetlepels verse basilicum of verse peterselie, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Linzen-Rijst-Linzenmix-Met-Doperwtjes-En-Groene-Asperges.jpg",
  "4"],
 ["Lassie","Rijst-notenburgers met hazelnoten of pinda&#039;s",
  "https://lassie.nl/recepten/zilvervliesrijst/rijst-notenburgers",
  "<ul><li> ½ rode paprika</li><li> 150 g hazelnoten of pinda’s</li><li> 1 bosuitje, in stukjes</li><li> 6 takjes verse peterselie, grof gehakt</li><li> 200 g gekookte<a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'> Lassie Zilvervliesrijst </a>(= 75 g ongekookte rijst)</li><li> 2 theelepels kerriepoeder</li><li> 2 eieren</li><li> 4 eetlepels olie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Rijst-Notenburgers.jpg",
  "4"],
 ["Lassie","Rijstfrittata met spinazie &amp; broccoli",
  "https://lassie.nl/recepten/zilvervliesrijst-quinoa-én-granen/rijstfrittata-met-spinazie-en-broccoli",
  "<ul><li>300 g<a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst-quinoa-%C3%A9n-granen'> Lassie Zilvervliesrijst + Quinoa en Granen</a> (275 g)</li><li>300 g broccoliroosjes</li><li>3 eetlepels olijfolie</li><li>2 grote tenen knoflook, fijngehakt</li><li>500 g panklare spinazie</li><li>6 eieren</li><li>75 g Parmezaanse kaas, vers geraspt</li><li>100 g Gorgonzola, in stukjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Quinoa-Granen-Rijstfrittata-Met-Spinazie-En-Broccoli.jpg",
  "4-6"],
 ["Lassie","Risotto Milanese met Parmezaanse kaas",
  "https://lassie.nl/recepten/risottorijst/risotto-milanese",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/risottorijst'>Lassie Risottorijst</a></li><li> 4 eetlepels olijfolie</li><li> 60 g boter</li><li> 1 ui, gesnipperd</li><li> 2 zakjes saffraandraadjes (a 0,05g)</li><li> 1 liter runderbouillon</li><li> 100 g Parmezaanse kaas, geraspt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Risottorijst-Risotto-Milanese.jpg",
  "4"],
 ["Lassie","Risotto Primavera met parmezaanse kaas ",
  "https://lassie.nl/recepten/risottorijst/risotto-primavera",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/risottorijst'>Lassie Risottorijst</a></li><li> 30 g boter</li><li> 4 eetlepels olijfolie</li><li> 1 ui, gesnipperd</li><li> 100 ml droge witte wijn</li><li> 1,2 liter groentebouillon </li><li> 1 venkel, in plakjes</li><li> 1 bos groene asperges, in stukjes</li><li> 1 courgette, in blokjes</li><li> 1 blik artisjokharten (400 g), uitgelekt</li><li> 4 eetlepels verse peterselie, fijngesneden</li><li> 75 g Parmezaanse kaas, geraspt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Risottorijst-Risotto-Primavera.jpg",
  "4"],
 ["Lassie","Risotto met spinazie en ei",
  "https://lassie.nl/recepten/risottorijst/spinazie-ei-geitenkaas",
  "<ul><li>1 venkelknol</li><li>3 eetlepels olijfolie</li><li>1 ui, gesnipperd</li><li>400 g Lassie <a target='_blank' href='https://lassie.nl/producten/risottorijst'>Risotto Rijst</a> </li><li>1 l groente- of kruidenbouillon</li><li>2 eetlepels verse oregano, fijngehakt</li><li>4 eieren</li><li>125 g zachte geitenkaas, verkruimeld</li><li>400 g spinazie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Risotto-Rijst-Risotto-Met-Spinazie-Ei-En-Geitenkaas.jpg",
  "4"],
 ["Lassie","Roerei met tijm, botersla en komkommer",
  "https://lassie.nl/recepten/toverrijst-voordeelverpakking/roerei-tijm-botersla-komkommer",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst-voordeelverpakking'>Lassie Toverrijst </a></li><li>4 tomaten, in stukjes </li><li>6 snackkomkommers, in plakjes </li><li>1 zak botersla, gewassen</li><li>50 g gemengde olijven zonder pit </li><li>4 eetlepels slasaus </li><li>8 eieren </li><li>3 takjes tijm, blaadjes gerist</li><li>2 eetlepels olie</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/456-Toverrijst-Roerei-tijm-en-frisse-zomerse-salade-kp.jpg",
  "4"],
 ["Lassie","Romige kipkerrie met doperwtjes",
  "https://lassie.nl/recepten/toverrijst-extra/romige-kipkerrie-met-doperwtjes",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/toverrijst-extra'> Lassie Toverrijst Extra vezels</a></li><li> 2 el olijfolie</li><li> 2 rode uien, in parten</li><li>400 g kip, in reepjes</li><li> 2 tl kerriepoeder</li><li> 2 el tarwebloem</li><li> 2 rode paprika’s, in reepjes</li><li> 200 ml crème fraîche</li><li> 250 g doperwtjes (diepvries)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Toverrijst-Extra-Romige-kip-kerrie-met-doperwtjes.jpg",
  "4"],
 ["Lassie","Romige risotto met champignons",
  "https://lassie.nl/recepten/rapido-risotto/romige-risotto-met-champignons",
  "<ul><li>350 gram <a target='_blank' href='https://lassie.nl/producten/rapido-risotto'>Rapido Risotto </a></li><li>1 klontje boter </li><li>1 kleine ui, gesnipperd</li><li>500 g champignons, in plakjes</li><li>500 ml groentebouillon</li><li>3 eetlepels crème fraîche</li><li>60 g geraspte Parmezaanse kaas</li><li>verse bieslook, fijngehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Rapido-Risotto-Romige-Risotto-Met-Champignons.jpg",
  "4"],
 ["Lassie","Stoofschotel van bietjes met gietenkaas",
  "https://lassie.nl/recepten/half-volkoren-toverrijst-voordeelverpakking/gestoofde-bietjes-geitenkaas-walnoten",
  "<ul><li>300 g Lassie <a target='_blank' href='https://lassie.nl/producten/half-volkoren-toverrijst-voordeelverpakking'>Half volkoren Toverrijst</a></li><li>2 eetlepels olie</li><li>150 g rode ui, gesneden </li><li>500 g gekookte bietjes, in partjes</li><li>1 biologische sinaasappel</li><li>125 ml crème fraîche </li><li>150 g verse geitenkaas, verbrokkeld</li><li>1 zakje rucola</li><li>75 g walnoten, geroosterd en grof gehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Half-Volkoren-Toverrijst-Stoofschotel-Van-Bietjes-Met-Geitenkaas-En-Walnoten.jpg",
  "4"],
 ["Lassie","Tomatencurry met eieren",
  "https://lassie.nl/recepten/basmatirijst-extra/tomatencurry-met-eieren",
  "<ul><li>300 g <a target='_blank' href='https://lassie.nl/producten/basmatirijst-extra'>Lassie Basmatirijst met extra vezels</a></li><li>6 eieren</li><li>3 eetlepels rijstolie</li><li>2 tenen knoflook, fijngehakt</li><li>1 eetlepel verse gember, geraspt</li><li>1 eetlepel Madras kerriepoeder</li><li>1-2 theelepels garam masala</li><li>400 g tomaten, in stukjes</li><li>400 g bimi</li><li>2 eetlepels verse koriander</li><li>2 eetlepels gebakken uitjes</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Basmati-Extra-Tomatencurry-Met-Eieren.jpg",
  "4"],
 ["Lassie","Traybake met herfstgroenten en bulgur",
  "https://lassie.nl/recepten/voorgestoomde-bulgur/baking-tray-herfst-groenten-walnoten-bulgur",
  "<ul><li>1 courgette, in blokken</li><li>400 g pompoenblokjes (1 zak) </li><li>½ theelepel gedroogde rozemarijn </li><li>3 eetlepels olie</li><li>2 trostomaten, gehalveerd </li><li>50 g walnoten </li><li>50 g verse geitenkaas met honing </li><li>1 zak <a target='_blank' href='https://lassie.nl/producten/voorgestoomde-bulgur'>voorgestoomde bulgur (250 g)</a></li></ul><ul><li>Extra nodig: bakplaat bekleed met bakpapier</li></ul><p>Optioneel:</p><ul><li>85 g rucola (zak)</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Notenrijst-Gebakken-harissa-zalm-notenrijst-spinazie.jpg",
  "2"],
 ["Lassie","Vega rijstlasagne met tofu en mozzarella",
  "https://lassie.nl/recepten/zilvervliesrijst/vega-rijstlasagne",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/zilvervliesrijst'>Lassie Zilvervliesrijst</a></li><li> 3 eetlepels olijfolie</li><li> 1 ui, gesnipperd</li><li> 2 tenen knoflook, geperst</li><li> 175 g vega gehakt (tofu of quorn)</li><li> 500 ml tomatensaus </li><li> 2 eetlepels gedroogde Italiaanse kruiden</li><li> 175 g geraspte mozzarella (pizzakaas)</li><li> 1 courgette, in lange plakken van ½ cm</li><li> 4 tomaten, gehalveerd</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Zilvervliesrijst-Vega-Rijstlasagne.jpg",
  "4"],
 ["Lassie","Vegaballetjes met preistoof en pindasaus",
  "https://lassie.nl/recepten/pandanrijst-extra/vegaballetjes-met-preistoof-en-pindasaus",
  "<ul><li> 2 builtjes <a target='_blank' href='https://lassie.nl/producten/builtjes-pandanrijst'>Lassie Builtjes Pandan</a></li><li> 2 dunne preien, in grove stukken</li><li> 1 rode paprika, grof gesneden </li><li> 175 g vega balletjes</li><li> 120 g satésaus kant en klaar</li><li> 1 zakje cassave kroepoek</li><li>2 eetlepels bakolie </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Pandanrijst-Builtjes-Vegaballetjes-Met-Preistoof-En-Pindasaus.jpg",
  "2"],
 ["Lassie","Vegetarische citroenrisotto met tuinbonen",
  "https://lassie.nl/recepten/risottorijst/citroenrisotto-met-tuinbonen",
  "<ul><li> 300 g <a target='_blank' href='https://lassie.nl/producten/risottorijst'>Lassie Risottorijst</a></li><li> 4 eetlepels olijfolie</li><li> 30 g boter</li><li> 1 ui, gesnipperd</li><li> 1 biologische citroen</li><li> 1 liter groentebouillon</li><li>400 g tuinbonen (diepvries)</li><li> 100 g Parmezaanse kaas, geraspt</li><li> ½ bosje verse munt, fijngesneden</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Risottorijst-Citroenrisotto-Met-Tuinbonen.jpg",
  "4"],
 ["Lassie","Vegetarische kipstukjes met boontjes",
  "https://lassie.nl/recepten/quinoa-mix-3-kleuren-quinoa/sperziebonen-vegetarische-kipstukjes-pittige-tomatensaus",
  "<ul><li>275 g <a target='_blank' href='https://lassie.nl/producten/quinoa-mix-3-kleuren-quinoa'>Lassie Quinoamix – 3 kleuren</a></li><li>4 eetlepels olie</li><li>400 g sperzieboontjes, gehalveerd</li><li>1 (gele) paprika, in lange repen</li><li>2 tenen knoflook, geperst</li><li>½ eetlepel paprikapoeder</li><li>1 theelepel gemalen komijn</li><li>500 g cocktailtomaten, in stukjes</li><li>1 eetlepel citroensap</li><li>320 g vegetarische kipstukjes </li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Quinoa-Mix-3-Kleuren-Sperziebonen-Vergetarische-Kipstukjes-En-Pittige-Tomatensaus.jpg",
  "4"],
 ["Lassie","Zilvervliesrijst met paddenstoelen en spinazie",
  "https://lassie.nl/recepten/panklaar-zilvervliesrijst/paddenstoelen-spinazie",
  "<ul><li>1 ui, in partjes</li><li>2 eetlepels olie</li><li>200 g paddenstoelen seizoenmelange, grof gesneden </li><li>½ eetlepel verse tijm</li><li>1 eetlepel verse oregano</li><li>1 pak <a target='_blank' href='https://lassie.nl/producten/panklaar-zilvervliesrijst'>Lassie Panklaar Zilvervliesrijst</a></li><li>125 g verse roomkaas met knoflook &amp; kruiden </li><li>200 g spinazie</li><li>25 g amandelen, grof gehakt</li></ul>",
  "https://lassie.nl/storage/images/recipe/_recipe/Panklaar-Zilvervliesrijst-Paddenstoelen-En-Spinazie.jpg",
  "2"],
]