var recepten = [
["_RCPT_ pasta met tomaten-ricottasaus (p.16) _FIN_","16",
 "3 tomaten, 1 ui, 1 teen knoflook, 4 el ricotta, 1 tl chilipoeder, 2 tl basilicum, 1 el tomatenpuree, half (groente)bouillonblokje, grote scheut water, 150 gr pasta"],
["_RCPT_ 15 minuten paprikasaus (p.20a) _FIN_","20a",
 "2 paprika's, 1 ui, 1 teen knoflook, 2 tl tomatenpuree, 1 tl italiaanse kruiden, snufje zout en peper, 250 ml (groente)bouillon, evt. allesbinder of maizena, 150 gr pasta"],
["_RCPT_ 15 minuten tomatensaus (p.20b) _FIN_","20b",
 "400 gr tomatenblokjes, 1 ui, 1 teen knoflook, 2 tl tomatenpuree, snufje zout en peper, 2 el italiaanse kruiden, evt. hamblokjes of gehakt, 150 gr pasta"],
["_RCPT_ koude pastasalade (p.27) _FIN_","27",
 "150 gr pasta, 1-2 tomaten, 2 el crème fraîche, 1/2 komkommer, 1 paprika, olijfolie, 1 tl tijm, 1 tl oregano, snufje zout en peper, 1 rode ui"],
["_RCPT_ macaroni-ovenschotel (p.31) _FIN_","31",
 "150 gr pasta, 300 gr verse spinazie, 1 ui, 1 teen knoflook, bakje cherrytomaten, geraspte kaas, olijfolie, 1 tl paprikapoeder, snufje zout en peper, 100 ml crème fraîche, boter of olijfolie (voor invetten)"],
["_RCPT_ pasta-ovenschotel met prei (p.35) _FIN_","35",
 "150 gr pasta, 200 gr tomatenblokjes, 70 gr tomatenpuree, 1 ui, 1 courgette, 2 tenen knoflook, 200 gr prei, olijfolie, snufje peper en zout, 1 el italiaanse kruiden, boter of olijfolie (voor invetten), 50 gr boter, 50 gr bloem, 500 ml melk, 1 handje geraspte kaas"],
["_RCPT_ pasta met courgette en champignons (p.36) _FIN_","36",
 "150 gr pasta, 100 ml crème fraîche, 150 gr champignons, halve/hele courgette, 1 paprika, 2 tenen knoflook, 1 ui, 1 el italiaanse kruiden, olijfolie, snufje zout en peper, handje geraspte kaas"],
["_RCPT_ pasta pesto met courgette (p.40) _FIN_","40",
 "150 gr pasta, 3 el paddenstoelen, 2 el crème fraîche, 1 courgette, 1 paprika, 1 ui, 1 teen knoflook, olijfolie, snufje zout en peper, parmezaanse kaas"],
["_RCPT_ panpizza (p.51) _FIN_","51",
 "4-5 boterhammen of een stuk turks brood, tomatensaus, 1 rode ui, 4-5 cherrytomaten, handje geraspte kaas, 1 bol mozzarella, 1 el italiaanse kruiden, olijfolie, eventueel pesto of ananas"],
["_RCPT_ italiaanse kaasfondue uit een broodje (p.52) _FIN_","52",
 "2 italiaanse bollen, 250 ml (groente)bouillon, 150 gr geraspte belegen kaas, 100 gr geraspte grana padano, 2 tl italiaanse kruiden, snufje zout en peper, paar lepels allesbinder of maizena, om te dippen:, broccoli, gebakken aardappeltjes, sperziebonen, cherrytomaten, stokbrood, enz"],
["_RCPT_ aardappelschotel met courgette (p.59) _FIN_","59",
 "450 gr krieltjes, 1 paprika, 3-4 el parmezaanse kaas, 1 bol mozzarella, 1 courgette, 2 el tijm, olijfolie, snufje zout en peper, cherrytomaten"],
["_RCPT_ vegetarische nachoschotel (p.64) _FIN_","64",
 "halve zak tortillachips, 1 paprika, 1 ui, 1 teen knoflook, 150 gr kidneybonen, 1 blikje mais (150 gr), 1 tl paprikapoeder, 200 gr tomatenblokjes, olijfolie, snufje zout en peper, handje geraspte kaas, boter of olijfolie (voor invetten)"],
["_RCPT_ zoete aardappelschotel (p.68) _FIN_","68",
 "250 gr sperziebonen, 3 zoete aardappeltjes, 100 gr doperwtjes (diepvries), 1 paprika, 200 ml kokosmelk, 1 ui, 1 rode peper, 1 tl kerrie, 1 tl paprikapoeder, olijfolie"],
["_RCPT_ italiaanse wraptaart (p.76) _FIN_","76",
 "6 wraps, 2 paprika's, 1 ui, 2 tl tomatenpuree, 1 rode peper, 400 gr tomatenblokjes, 1 el italiaanse kruiden, 1 bol gesneden mozzarella, 2 el crème fraîche, bakje cherrytomaten, 50 gr geraspte kaas, olijfolie, boter of olijfolie (voor invetten)"],
["_RCPT_ pittige quesadilla's met kidneybonen (p.80) _FIN_","80",
 "150 gr kidneybonen uit blik, 2 bosuien, 1 rode peper, 1 ui, 1 teen knoflook, 50 gr geraspte kaas, olijfolie, snufje zout en peper, 2 el tomatenpuree"],
["_RCPT_ avocado quesadilla's (p.83) _FIN_","83",
 "8 wraps, 2 tomaten, 1 bosui, 2 avocado's, 2 tl crème fraîche, 1 teen knoflook, scheutje citroensap, olijfolie, snufje zout en peper, 50 gr geraspte kaas"],
["_RCPT_ flammkuchenwraps met paprika (p.88) _FIN_","88",
 "4 wraps, 4 tl crème fraîche, 1 ui, 2 geroosterde paprika's (uit een pot), 50 gr rucola, 75 gr geitenkaas, snufje zwarte peper"],
["_RCPT_ komkommersalade met bleekselederij (p.99) _FIN_","99",
 "halve komkommer, 1 takje verse dille, 2 stengels bleekselderij, snufje zout en peper, 2 el griekse yoghurt"],
["_RCPT_ mediterrane aardappelsalade (p.100) _FIN_","100",
 "3 aardappels, 1 bakje cherrytomaten / 2 tomaten, 50 gr feta, halve komkommer, 1 bosui, halve rode ui, 1 paprika, 1 tl oregano, 2 el griekse yoghurt, olijfolie, snufje zout en peper"],
["_RCPT_ snelle spitskoolsalade (p.103) _FIN_","103",
 "300 gr spitskool, 1 appel, 50 gr walnoten, 100-150 gr rode druiven, 1 avocado, 1 el mayonaise, 1 el griekse yoghurt"],
["_RCPT_ pompoensalade (p.108) _FIN_","108",
 "1 rode ui, 100 gr rucola, 2 el amandelschaafsel, 6 zongedroogde tomaten, 500 gr pompoenblokjes, 2 el parmezaanse kaas, 1 el olijfolie, snufje zout en peper, 1 tl basilicum"],
["_RCPT_ gado gado-salade (p.111) _FIN_","111",
 "2 eieren, 200 gr sperziebonen, 100 gr taugé, 200 gr wortels, 200 spitskool, pindasaus, halve komkommer, olijfolie"],
["_RCPT_ salade met geroosterde groenten (p.116) _FIN_","116",
 "1 courgette, 1 aubergine, 1 puntpaprika, 1 (rode) ui, 2 el oregano, olijfolie, snufje zout en peper, 100 gr rijst/bulgur/couscous, scheutje citroen- of limoensap"],
["_RCPT_ witlofsalade met walnoten (p.119a) _FIN_","119a",
 "4 stronkjes witlof, 1 appel, scheut citroensap, 2 handjes rozijnen, 2 handjes walnoten, 100 ml yoghurt, snufje zout en peper"],
["_RCPT_ witlofsalade met mandarijn (p.119b) _FIN_","119b",
 "4 stronkjes witlof, 2 mandarijnen, scheut citroensap, 2 handjes rozijnen, 2 handjes hazelnoten, 2 el mayonaise, 2 el yoghurt, snufje zout en peper"],
["_RCPT_ broodsalade (p.120) _FIN_","120",
 "2 pistoletjes (of ander brood), 100 gr rucola, bakje cherrytomaten, 1 rode ui, halve/hele komkommer, takje verse basilicum, olijfolie, snufje zout en peper"],
["_RCPT_ griekse salade met gebakken feta (p.123) _FIN_","123",
 "100 gr feta, 1 ei, bloem, snufje zout en peper, 1 paprika, halve/hele komkommer, 1 kleine rode ui, bakje cherrytomaten, olijfolie, 1 tl oregano, eventueel olijven"],
["_RCPT_ pastasalade met brie (p.124) _FIN_","124",
 "150 gr pasta, 100 gr brie, 5-6 zongedroogde tomaten, 75 gr veldsla, 1 el honing, 1,5 el mosterd, 1,5 rode ui"],
["_RCPT_ rode linzensoep (p.131) _FIN_","131",
 "150 gr gedroogde roze linzen, 1-2 tenen knoflook, 1 kleine ui, 1 paprika, 400 gr tomatenblokjes, 1 tl kerrie, 1 tl paprikapoeder, olijfolie, snufje zwarte peper, ca. 750 ml water, 1 (groente)bouillonblokje, eventueel mascarpone"],
["_RCPT_ pittige pompoensoep (p.132) _FIN_","132",
 "400 gr pompoenblokjes, 1 rode peper, 1 kleine ui, 2 tenen knoflook, 500 ml (groente)bouillon, 1 grote aardappel, 1 tl tijm, 1 tl kerriepoeder, olijfolie, snufje zout en peper"],
["_RCPT_ zongedrooge tomatensoep (p.135a) _FIN_","135a",
 "1 ui, 1 teen knoflook, 10 zongedroogde tomaten, 200 gr tomatenblokjes, 400 ml (groente)bouillon, 1 el tomatenpuree, olijfolie, snufje zout en peper, 1 tl basilicum, 1 tl oregano"],
["_RCPT_ pittige zongedrooge tomatensoep (p.135b) _FIN_","135b",
 "1 ui, 2 tenen knoflook, 10 zongedroogde tomaten, 200 gr tomatenblokjes, 400 ml (groente)bouillon, 1 el tomatenpuree, olijfolie, 1 tl paprikapoeder, snufje komijn"],
["_RCPT_ broccolisoep (p.139) _FIN_","139",
 "500 gr broccoli, 1 ui, 1 teen knoflook, 1-2 aardappels, 1 (groente)bouillonblokje, 500 ml water, 200 gr prei, 1 el tijm, 1 el peterselie, olijfolie, snufje zout en peper, eventueel crème fraîche"],
["_RCPT_ romige bloemkoolsoep (p.140) _FIN_","140",
 "1 bloemkool, 1 ui, 2 tenen knoflook, 100 ml kookroom, 1 el tijm, halve tl nootmuskaat, 2 (groente)bouillonblokjes, 1 liter water, 1 aardappel, olijfolie, snufje zout en peper"],
["_RCPT_ wortelsoep met gember (p.144) _FIN_","144",
 "500 gr wortels, 600-700 ml water, 1 (groente)bouillonblokje, 1 ui, 2 tenen knoflook, stukje gember (ca. 5 cm), 100 ml kokosmelk, olijfolie, snufje zout en peper, takje verse koriander"],
["_RCPT_ paprika-tomatensoep (p.147a) _FIN_","147a",
 "3-4 tomaten, 3 tl tomatenpuree, 1 paprika, 1 ui, 1 (groente)bouillonblokje, 750 ml water, 1 tl italiaanse kruiden, snufje zwarte peper, snufje chilipoeder, olijfolie"],
["_RCPT_ geroosterde paprikasoep (p.147b) _FIN_","147b",
 "3-4 tomaten, 3 tl tomatenpuree, 2 geroosterde paprika's uit blik, 1 ui, 1 rode peper, 1 teen knoflook, 1 (groente)bouillonblokje, 750 ml water, snufje zwarte peper, olijfolie"],
["_RCPT_ zoete aardappelsoep (p.148) _FIN_","148",
 "2 grote zoete aardappels, 1 ui, 1 teen knoflook, 1 rode peper, 100 ml kokosmelk, 1 liter water, 2 (groente)bouillonblokjes, olijfolie, snufje zout en peper, 1 tl paprikapoeder, 1 tl kerriepoeder, verse koriander"],
["_RCPT_ ravioli-ovenschotel met mascarpone (p.164) _FIN_","164",
 "250 gr (verse) ravioli, 400 gr tomatenblokjes, 4 el mascarpone, 1 ui, 2 paprika's, 1 el italiaanse kruiden, olijfolie, snufje zout en peper, 50 gr geraspte kaas, eventueel cherrytomaten, boter of olijfolie (voor invetten)"],
["_RCPT_ bloemkoolfrittata (p.179a) _FIN_","179a",
 "3 eieren, 100 ml melk, 1 ui, 400 gr bloemkoolroosjes, bakje cherrytomaten, 1 paprika, 1 tl paprikapoeder, 1 tl kerriepoeder, snufje zout en peper, 30 gr geraspte kaas, boter of olijfolie (voor invetten)"],
["_RCPT_ aardappelfrittata met spinazie (p.179b) _FIN_","179b",
 "3 eieren, 100 ml melk, 1 ui, 1 teen knoflook, 300 gr spinazie, 10 cherrytomaten, 1 tl paprikapoeder, olijfolie, snufje zout en peper, 30 gr geraspte kaas, boter of olijfolie (voor invetten)"],
["_RCPT_ plaattaart met tomaat en mozzarella (p.191) _FIN_","191",
 "6 velletjes bladerdeeg (ontdooid), 4 tomaten, 1 bol mozzarella, 4 el pesto, 1 el italiaanse kruiden, snufje zout en peper, rucola"],
["_RCPT_ pompoentaart met prei en geitenkaas (p.192) _FIN_","192",
 "300 gr pompoenblokjes, 1 ui, 200 gr prei, 50 gr geitenkaas, scheutje honing, olijfolie, snufje zout en peper, 3 eieren, scheut melk, 5 plakjes bladerdeeg, boter of olijfolie (voor invetten)"],
["_RCPT_ gevulde tomaten met rijst (p.195) _FIN_","195",
 "4 vleestomaten of 8 kleine tomaten, 100 gr rijst, 1 ui, 2 tenen knoflook, 100 gr prei, 1 el dille, olijfolie, snufje zout en peper, handjes geraspte kaas, boter of olijfolie (voor invetten)"],
["_RCPT_ simpele melanzane (p.204) _FIN_","204",
 "2 aubergine's, 200 gr tomatensaus, 1 ui, 1 bol mozzarella, 10 cherrytomaten, 2 el italiaanse kruiden, olijfolie, snufje zout en peper, 1 paprika, boter of olijfolie (voor invetten)"],
["_RCPT_ snelle nasi (p.220a) _FIN_","220a",
 "150 gr rijst, 1 ui, 2 tenen knoflook, scheutje ketjap manis, 1 rode peper, 2 tl nasi kruidenmix, 1 paprika, halve courgette, halve prei, halve aubergine, olijfolie, eventueel 1-2 eieren, serveren met:, verse bosui, satesaus, kroepoek, gebakken uitjes"],
["_RCPT_ snelle bami (p.220b) _FIN_","220b",
 "200 gr mie, 1 ui, 2 tenen knoflook, 1 rode peper, scheutje ketjap manis, 1 el bami kruidenmix, 300 gr oosterse wokgroenten, olijfolie, 2 eieren"],
["_RCPT_ sperziebonen in tomatensaus (p.232) _FIN_","232",
 "150 gr rijst, 400 gr tomatenblokjes, 400 gr sperziebonen, 1 ui, 1 rode peper, 1 teen knoflook, 100-200 ml water, 1 tl paprikapoeder, halve tl komijn, olijfolie, snufje zout en peper, verse peterselie"],
["_RCPT_ plaattaart met paddenstoelen (p.243) _FIN_","243",
 "6 plakjes bladerdeeg, 200 gr paddenstoelenmelange, 1 bekertje crème fraîche, olijfolie, 2 tl tijm, snufje zout en peper, snufje knoflookpoeder"],
["_RCPT_ pitabroodjes met ei (p.256) _FIN_","256",
 "6 pitabroodjes, 3 eieren, scheut melk, 1 ui, 1 paprika, 1 el italiaanse kruiden, 200 gr prei, roomkaas met kruiden, 50 gr rucola, olijfolie"],
["_RCPT_ rucolastamppot (p.271) _FIN_","271",
 "450 gr kruimige aardappels, 50 gr rucola, 1 rode ui, 6-8 zongedroogde tomaten, pijnboompitten, parmezaanse kaas, olijfolie, snufje zout en peper, 2 tl crème fraîche"],
["_RCPT_ pitabroodjes met peultjes (p.295) _FIN_","295",
 "6 pitabroodjes, 400 gr kikkererwten uit blik, 1 tl paprikapoeder, snufje komijn, snufje zout en peper, snufje knoflookpoeder, olijfolie, 1 ui, 1 rode peper, 200 gr peultjes, eventueel 1 paprika"],
["_RCPT_ vegetarische courgetteburgers (p.296) _FIN_","296",
 "1 courgette, 1 ei, 1 kleine ui, 1 teen knoflook, 5 el bloem, 2 el paneermeel, olijfolie, snufje zout en peper, handje geraspte kaas, 4 (hamburger)broodjes, 1-2 tomaten, 1 paprika, rucola/sla, komkommer"],
["_RCPT_ zoete aardappelstamppot met rucola (p.299a) _FIN_","299a",
 "4-5 zoete aardappels, 1 paprika, 50 gr rucola, 2 el pijnboompitten, snufje zout en peper, olijfolie, 100 gr vegetarische spekreepjes"],
["_RCPT_ zoete aardappelstamppot met spinazie (p.299b) _FIN_","299b",
 "4-5 zoete aardappels, 1 paprika, 100 gr spinazie, 1 ui, 2 el pijnboompitten, olijfolie, snufje zout en peper"],
["_RCPT_ bloemkool met kaas uit de oven (p.300) _FIN_","300",
 "1 bloemkool, 2 plakken kaas, 2 tl italiaanse kruiden, snufje knoflookpoeder, snufje zout en peper"],
["_RCPT_ pizzabroodjes (p.303) _FIN_","303",
 "4 afbakbroodjes, 70 gr tomatenpuree, 1 paprika, 1 blikje ananas, 2 handjes geraspte kaas, 1 el italiaanse kruiden, 1 kleine ui"],
["_RCPT_ naanbroodjes met courgette (p.304a) _FIN_","304a",
 "4 naanbroodjes, 4 el tomatenpuree of 8 el tomatensaus, 1 paprika, 1 ui, halve courgette, 50 gr rucola, 1 el tijm, 1 el oregano, snufje zout en peper, 50 gr geraspte kaas"],
["_RCPT_ mexicaanse naanbroodjes (p.304b) _FIN_","304b",
 "4 naanbroodjes, 200 gr tomatensaus, 100 gr maiskorrels (blikje), 1 ui, 100 gr kidneybonen, snufje cayennepeper, 1 tl paprikapoeder, halve tl knoflookpoeder, snufje zout en peper, 50 gr geraspte kaas"],
["_RCPT_ gevulde puntpaprika's met geitenkaas (p.307) _FIN_","307",
 "2 puntpaprika's, 100-150 gr geitenkaas, 1 bosui, snufje zout en peper, 1 el peterselie"],
["_RCPT_ paprikapannenkoeken (p.308) _FIN_","308",
 "250 ml melk, 1 ei, 125 gr bloem, 30 gr geraspte kaas, 1 paprika, 1 tl paprikapoeder, olijfolie, snufje zout en peper, roomkaas met kruiden, 100 gr vegetarische kipstukjes"],
["_RCPT_ griekse stamppot (p.311a) _FIN_","311a",
 "450 gr kruimige aardappels, bakje cherrytomaten, 100 gr feta, 2 paprika's, 1 rode ui, 1 el gedroogde basilicum, snufje zout en peper"],
["_RCPT_ pittige nasistamppot (p.311b) _FIN_","311b",
 "450 kruimige aardappels, 1 prei, 1 ui, 200 gr wortels, 1,5 el sambal, 2 el nasikruiden"],
["_RCPT_ snelle curry met bloemkool (p.312) _FIN_","312",
 "150-200 gr rijst, 200 gr bloemkool, 2 eieren, 1 ui, 1 teen knoflook, 200 ml kokosmelk, 1-2 tl rode curry, 1 paprika, olijfolie"],
["_RCPT_ courgettetaart met geitenkaas (p.315) _FIN_","315",
 "5 plakjes hartig taartdeeg (of bladerdeeg), 1 courgette, 1 paprika, 1 ui, 2 eieren, 150 ml kookroom, 75 gr roomkaas, snufje zout en peper, 1 el basilicum, 1 el oregano, 6 cherrytomaten, boter of olijfolie (voor invetten)"],
["_RCPT_ röstikoek met paprika (p.316) _FIN_","316",
 "3 aardappels, 1 paprika, halve/hele courgette, 1 kleine ui, 1 ei, 1 tl paprikapoeder, 1 tl tijm, olijfolie, snufje zout en peper"],
["_RCPT_ quiche caprese (p.319) _FIN_","319",
 "5 plakjes bladerdeeg (ontdooid), 10 zongedroogde tomaten, 1 bol mozzarella, 2 eieren, 200 ml kookroom, 1 el gedroogde basilicum, snufje zout en peper, 1 ui, paneermeel, 50 gr geraspte kaas, boter of olijfolie (voor invetten)"],
]